// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_b6_V_H__
#define __dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_b6_V_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_b6_V_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 10;
  static const unsigned AddressRange = 128;
  static const unsigned AddressWidth = 7;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_b6_V_ram) {
        ram[0] = "0b1111111001";
        ram[1] = "0b1110100100";
        ram[2] = "0b0001000010";
        ram[3] = "0b1111111001";
        ram[4] = "0b1111110010";
        ram[5] = "0b1111110100";
        ram[6] = "0b1111111001";
        ram[7] = "0b1111111001";
        ram[8] = "0b1111111001";
        ram[9] = "0b1111110111";
        ram[10] = "0b1111111011";
        ram[11] = "0b1111111001";
        ram[12] = "0b0000000001";
        ram[13] = "0b1000001101";
        ram[14] = "0b1101000100";
        ram[15] = "0b1111101111";
        ram[16] = "0b1111111001";
        ram[17] = "0b1111111010";
        ram[18] = "0b0010011100";
        ram[19] = "0b1111111000";
        ram[20] = "0b1111110110";
        ram[21] = "0b1111101101";
        ram[22] = "0b1111111001";
        ram[23] = "0b1111111001";
        ram[24] = "0b1111101100";
        ram[25] = "0b1111111001";
        ram[26] = "0b0000111110";
        ram[27] = "0b1111111001";
        ram[28] = "0b0000001111";
        ram[29] = "0b1110001001";
        ram[30] = "0b1111110001";
        ram[31] = "0b1111111001";
        ram[32] = "0b1000110010";
        ram[33] = "0b1111111001";
        ram[34] = "0b1101011010";
        ram[35] = "0b1111110111";
        ram[36] = "0b0001000110";
        ram[37] = "0b0000010100";
        ram[38] = "0b1111111000";
        ram[39] = "0b1111111001";
        ram[40] = "0b1111100110";
        ram[41] = "0b1001000111";
        ram[42] = "0b1111111001";
        ram[43] = "0b1111111001";
        ram[44] = "0b1111101010";
        ram[45] = "0b1111111010";
        ram[46] = "0b1111100110";
        ram[47] = "0b1111010100";
        ram[48] = "0b1111111001";
        ram[49] = "0b0001101101";
        ram[50] = "0b1000000011";
        ram[51] = "0b1111111001";
        ram[52] = "0b1111111001";
        ram[53] = "0b1111101011";
        ram[54] = "0b1101101110";
        ram[55] = "0b0011000101";
        ram[56] = "0b1111101111";
        ram[57] = "0b1111111000";
        ram[58] = "0b1111011100";
        ram[59] = "0b1111111010";
        ram[60] = "0b1111110010";
        ram[61] = "0b1111111001";
        ram[62] = "0b1111111001";
        ram[63] = "0b1111111001";
        ram[64] = "0b1011100011";
        ram[65] = "0b1111111010";
        ram[66] = "0b0001011100";
        ram[67] = "0b1111100101";
        ram[68] = "0b1111111011";
        ram[69] = "0b1111100011";
        ram[70] = "0b1111111001";
        ram[71] = "0b0001101110";
        ram[72] = "0b1111111001";
        ram[73] = "0b1101010111";
        ram[74] = "0b1111111000";
        ram[75] = "0b1111111010";
        ram[76] = "0b1111110101";
        ram[77] = "0b1111011000";
        ram[78] = "0b1111101000";
        ram[79] = "0b1111111001";
        ram[80] = "0b0000001110";
        ram[81] = "0b1111111001";
        ram[82] = "0b1111111001";
        ram[83] = "0b1111111001";
        ram[84] = "0b0000000111";
        ram[85] = "0b1111111001";
        ram[86] = "0b1111000010";
        ram[87] = "0b1111111001";
        ram[88] = "0b1111111011";
        ram[89] = "0b1111111001";
        ram[90] = "0b1111111001";
        ram[91] = "0b1111111001";
        ram[92] = "0b0001010101";
        ram[93] = "0b1111111001";
        ram[94] = "0b1111111001";
        ram[95] = "0b1111011001";
        ram[96] = "0b1111011100";
        ram[97] = "0b1111101100";
        ram[98] = "0b1110111001";
        ram[99] = "0b1101010011";
        ram[100] = "0b1111111001";
        ram[101] = "0b0110110010";
        ram[102] = "0b1111111001";
        ram[103] = "0b1011010111";
        ram[104] = "0b1111111001";
        ram[105] = "0b0001111101";
        ram[106] = "0b1111111100";
        ram[107] = "0b0011000111";
        ram[108] = "0b1111111010";
        ram[109] = "0b1111111101";
        ram[110] = "0b1111111011";
        ram[111] = "0b0000010001";
        ram[112] = "0b1111111010";
        ram[113] = "0b1111011101";
        ram[114] = "0b1111111001";
        ram[115] = "0b1111111011";
        ram[116] = "0b1111111001";
        ram[117] = "0b1111110010";
        ram[118] = "0b1110000010";
        ram[119] = "0b1111111001";
        ram[120] = "0b1111111001";
        ram[121] = "0b1110101111";
        ram[122] = "0b1111111010";
        ram[123] = "0b1111111011";
        ram[124] = "0b1111110111";
        ram[125] = "0b1110001010";
        ram[126] = "0b1111100110";
        ram[127] = "0b1111111001";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_b6_V) {


static const unsigned DataWidth = 10;
static const unsigned AddressRange = 128;
static const unsigned AddressWidth = 7;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_b6_V_ram* meminst;


SC_CTOR(dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_b6_V) {
meminst = new dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_b6_V_ram("dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_b6_V_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_b6_V() {
    delete meminst;
}


};//endmodule
#endif
