// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state1 = "1";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state2 = "10";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state3 = "100";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state4 = "1000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state5 = "10000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state6 = "100000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state7 = "1000000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state8 = "10000000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state9 = "100000000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state10 = "1000000000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state11 = "10000000000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state12 = "100000000000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<24> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_11 = "10001";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_15 = "10101";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_1 = "1";
const sc_lv<1> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv1_0 = "0";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_2 = "10";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_3 = "11";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_4 = "100";
const sc_lv<1> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv1_1 = "1";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_5 = "101";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_6 = "110";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_7 = "111";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_9 = "1001";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_B = "1011";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_C = "1100";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_E = "1110";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_F = "1111";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_10 = "10000";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_12 = "10010";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_14 = "10100";
const sc_lv<13> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv13_0 = "0000000000000";
const sc_lv<27> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv27_0 = "000000000000000000000000000";
const sc_lv<8> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv8_0 = "00000000";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_A = "1010";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_D = "1101";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_13 = "10011";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_17 = "10111";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_16 = "10110";
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv4_6 = "110";
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv4_5 = "101";
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv4_4 = "100";
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv4_3 = "11";
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv4_2 = "10";
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv4_1 = "1";
const sc_lv<4> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv4_0 = "0000";
const sc_lv<27> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv27_2E8C = "10111010001100";
const sc_lv<13> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv13_1600 = "1011000000000";
const sc_lv<13> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv13_1 = "1";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_1A = "11010";
const sc_lv<7> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv7_0 = "0000000";
const sc_lv<8> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv8_80 = "10000000";
const sc_lv<8> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv8_1 = "1";
const sc_lv<13> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv13_2C0 = "1011000000";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_lv32_19 = "11001";
const bool dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::ap_const_boolean_1 = true;

dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    w6_V_U = new dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_w6_V("w6_V_U");
    w6_V_U->clk(ap_clk);
    w6_V_U->reset(ap_rst);
    w6_V_U->address0(w6_V_address0);
    w6_V_U->ce0(w6_V_ce0);
    w6_V_U->q0(w6_V_q0);
    b6_V_U = new dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_b6_V("b6_V_U");
    b6_V_U->clk(ap_clk);
    b6_V_U->reset(ap_rst);
    b6_V_U->address0(b6_V_address0);
    b6_V_U->ce0(b6_V_ce0);
    b6_V_U->q0(b6_V_q0);
    mult_V_U = new dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_mult_V("mult_V_U");
    mult_V_U->clk(ap_clk);
    mult_V_U->reset(ap_rst);
    mult_V_U->address0(mult_V_address0);
    mult_V_U->ce0(mult_V_ce0);
    mult_V_U->we0(mult_V_we0);
    mult_V_U->d0(mult_V_d0);
    mult_V_U->q0(mult_V_q0);
    acc_V_U = new dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_acc_V("acc_V_U");
    acc_V_U->clk(ap_clk);
    acc_V_U->reset(ap_rst);
    acc_V_U->address0(acc_V_address0);
    acc_V_U->ce0(acc_V_ce0);
    acc_V_U->we0(acc_V_we0);
    acc_V_U->d0(acc_V_d0);
    acc_V_U->q0(acc_V_q0);
    myproject_mux_832_16_1_1_U594 = new myproject_mux_832_16_1_1<1,1,16,16,16,16,16,16,16,16,32,16>("myproject_mux_832_16_1_1_U594");
    myproject_mux_832_16_1_1_U594->din0(data_0_V_load_reg_810);
    myproject_mux_832_16_1_1_U594->din1(data_1_V_load_reg_815);
    myproject_mux_832_16_1_1_U594->din2(data_2_V_load_reg_820);
    myproject_mux_832_16_1_1_U594->din3(data_3_V_load_reg_825);
    myproject_mux_832_16_1_1_U594->din4(data_4_V_load_reg_830);
    myproject_mux_832_16_1_1_U594->din5(data_5_V_load_reg_835);
    myproject_mux_832_16_1_1_U594->din6(data_6_V_load_reg_840);
    myproject_mux_832_16_1_1_U594->din7(data_7_V_load_reg_845);
    myproject_mux_832_16_1_1_U594->din8(cache_V_fu_544_p9);
    myproject_mux_832_16_1_1_U594->dout(cache_V_fu_544_p10);
    myproject_mul_mul_16s_11s_26_3_1_U595 = new myproject_mul_mul_16s_11s_26_3_1<1,3,16,11,26>("myproject_mul_mul_16s_11s_26_3_1_U595");
    myproject_mul_mul_16s_11s_26_3_1_U595->clk(ap_clk);
    myproject_mul_mul_16s_11s_26_3_1_U595->reset(ap_rst);
    myproject_mul_mul_16s_11s_26_3_1_U595->din0(grp_fu_747_p0);
    myproject_mul_mul_16s_11s_26_3_1_U595->din1(w6_V_load_reg_888);
    myproject_mul_mul_16s_11s_26_3_1_U595->ce(ap_var_for_const0);
    myproject_mul_mul_16s_11s_26_3_1_U595->dout(grp_fu_747_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_OP1_V_cast_fu_566_p1);
    sensitive << ( cache_V_fu_544_p10 );

    SC_METHOD(thread_acc_V_address0);
    sensitive << ( tmp_229_reg_911 );
    sensitive << ( acc_V_addr_4_reg_952 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( tmp_236_fu_716_p1 );

    SC_METHOD(thread_acc_V_ce0);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_acc_V_d0);
    sensitive << ( p_Val2_s_62_reg_967 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( b6_V_load_cast_fu_645_p1 );

    SC_METHOD(thread_acc_V_we0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_231_fu_704_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_231_fu_704_p2 );

    SC_METHOD(thread_b6_V_address0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_229_fu_640_p1 );

    SC_METHOD(thread_b6_V_ce0);
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_b6_V_load_cast_fu_645_p1);
    sensitive << ( b6_V_load_reg_921 );

    SC_METHOD(thread_cache_V_fu_544_p9);
    sensitive << ( tmp_466_reg_765 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_data_0_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( newIndex7_fu_529_p1 );

    SC_METHOD(thread_data_0_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_data_1_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( newIndex7_fu_529_p1 );

    SC_METHOD(thread_data_1_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_data_2_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( newIndex7_fu_529_p1 );

    SC_METHOD(thread_data_2_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_data_3_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( newIndex7_fu_529_p1 );

    SC_METHOD(thread_data_3_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_data_4_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( newIndex7_fu_529_p1 );

    SC_METHOD(thread_data_4_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_data_5_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( newIndex7_fu_529_p1 );

    SC_METHOD(thread_data_5_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_data_6_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( newIndex7_fu_529_p1 );

    SC_METHOD(thread_data_6_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_data_7_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( newIndex7_fu_529_p1 );

    SC_METHOD(thread_data_7_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_grp_fu_747_p0);
    sensitive << ( OP1_V_cast_reg_855 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_iacc_2_fu_634_p2);
    sensitive << ( iacc_reg_444 );

    SC_METHOD(thread_idx_urem_fu_603_p3);
    sensitive << ( next_urem_fu_591_p2 );
    sensitive << ( tmp_467_fu_597_p2 );

    SC_METHOD(thread_ii_7_fu_513_p2);
    sensitive << ( ii_reg_398 );

    SC_METHOD(thread_ii_8_fu_655_p2);
    sensitive << ( ii2_reg_455 );

    SC_METHOD(thread_index_2_fu_685_p2);
    sensitive << ( tmp_232_reg_934 );
    sensitive << ( jj3_cast_fu_669_p1 );

    SC_METHOD(thread_index_fu_586_p2);
    sensitive << ( tmp_227_reg_850 );
    sensitive << ( jj_cast_fu_570_p1 );

    SC_METHOD(thread_ires_2_fu_710_p2);
    sensitive << ( ires_reg_477 );

    SC_METHOD(thread_jj3_cast_fu_669_p1);
    sensitive << ( jj3_reg_466 );

    SC_METHOD(thread_jj_3_fu_580_p2);
    sensitive << ( jj_reg_433 );

    SC_METHOD(thread_jj_4_fu_679_p2);
    sensitive << ( jj3_reg_466 );

    SC_METHOD(thread_jj_cast_fu_570_p1);
    sensitive << ( jj_reg_433 );

    SC_METHOD(thread_mult_V_address0);
    sensitive << ( tmp_233_reg_878 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( tmp_239_fu_695_p1 );

    SC_METHOD(thread_mult_V_ce0);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_mult_V_d0);
    sensitive << ( p_Val2_s_reg_898 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_mult_V_we0);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_newIndex7_fu_529_p1);
    sensitive << ( phi_urem_reg_421 );

    SC_METHOD(thread_newIndex8_fu_735_p1);
    sensitive << ( tmp_468_fu_731_p1 );

    SC_METHOD(thread_next_mul_fu_501_p2);
    sensitive << ( phi_mul_reg_410 );

    SC_METHOD(thread_next_urem_fu_591_p2);
    sensitive << ( phi_urem_reg_421 );

    SC_METHOD(thread_p_Val2_s_62_fu_699_p2);
    sensitive << ( reg_489 );
    sensitive << ( p_Val2_28_reg_962 );

    SC_METHOD(thread_res_0_V_address0);
    sensitive << ( res_0_V_addr_reg_989 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_0_V_ce0);
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_0_V_d0);
    sensitive << ( reg_489 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_0_V_we0);
    sensitive << ( arrayNo4_cast_reg_985 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_1_V_address0);
    sensitive << ( res_1_V_addr_reg_994 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_1_V_ce0);
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_1_V_d0);
    sensitive << ( reg_489 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_1_V_we0);
    sensitive << ( arrayNo4_cast_reg_985 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_2_V_address0);
    sensitive << ( res_2_V_addr_reg_999 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_2_V_ce0);
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_2_V_d0);
    sensitive << ( reg_489 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_2_V_we0);
    sensitive << ( arrayNo4_cast_reg_985 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_3_V_address0);
    sensitive << ( res_3_V_addr_reg_1004 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_3_V_ce0);
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_3_V_d0);
    sensitive << ( reg_489 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_3_V_we0);
    sensitive << ( arrayNo4_cast_reg_985 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_4_V_address0);
    sensitive << ( res_4_V_addr_reg_1009 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_4_V_ce0);
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_4_V_d0);
    sensitive << ( reg_489 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_4_V_we0);
    sensitive << ( arrayNo4_cast_reg_985 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_5_V_address0);
    sensitive << ( res_5_V_addr_reg_1014 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_5_V_ce0);
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_5_V_d0);
    sensitive << ( reg_489 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_5_V_we0);
    sensitive << ( arrayNo4_cast_reg_985 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_6_V_address0);
    sensitive << ( res_6_V_addr_reg_1019 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_6_V_ce0);
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_6_V_d0);
    sensitive << ( reg_489 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_6_V_we0);
    sensitive << ( arrayNo4_cast_reg_985 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_7_V_address0);
    sensitive << ( res_7_V_addr_reg_1024 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_7_V_ce0);
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_7_V_d0);
    sensitive << ( reg_489 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_res_7_V_we0);
    sensitive << ( arrayNo4_cast_reg_985 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_tmp_227_fu_558_p3);
    sensitive << ( ii_reg_398 );

    SC_METHOD(thread_tmp_228_fu_649_p2);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ii2_reg_455 );

    SC_METHOD(thread_tmp_229_fu_640_p1);
    sensitive << ( iacc_reg_444 );

    SC_METHOD(thread_tmp_230_fu_574_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( jj_reg_433 );

    SC_METHOD(thread_tmp_231_fu_704_p2);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ires_reg_477 );

    SC_METHOD(thread_tmp_232_fu_661_p3);
    sensitive << ( ii2_reg_455 );

    SC_METHOD(thread_tmp_233_fu_611_p1);
    sensitive << ( index_reg_868 );

    SC_METHOD(thread_tmp_236_fu_716_p1);
    sensitive << ( ires_reg_477 );

    SC_METHOD(thread_tmp_237_fu_673_p2);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( jj3_reg_466 );

    SC_METHOD(thread_tmp_238_fu_690_p1);
    sensitive << ( jj3_reg_466 );

    SC_METHOD(thread_tmp_239_fu_695_p1);
    sensitive << ( index_2_reg_947 );

    SC_METHOD(thread_tmp_467_fu_597_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_230_fu_574_p2 );
    sensitive << ( next_urem_fu_591_p2 );

    SC_METHOD(thread_tmp_468_fu_731_p1);
    sensitive << ( ires_reg_477 );

    SC_METHOD(thread_tmp_fu_507_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ii_reg_398 );

    SC_METHOD(thread_tmp_s_fu_628_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( iacc_reg_444 );

    SC_METHOD(thread_w6_V_address0);
    sensitive << ( tmp_233_fu_611_p1 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_w6_V_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_507_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_230_fu_574_p2 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_s_fu_628_p2 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( tmp_228_fu_649_p2 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( tmp_237_fu_673_p2 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_231_fu_704_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_address0, "(port)data_0_V_address0");
    sc_trace(mVcdFile, data_0_V_ce0, "(port)data_0_V_ce0");
    sc_trace(mVcdFile, data_0_V_q0, "(port)data_0_V_q0");
    sc_trace(mVcdFile, data_1_V_address0, "(port)data_1_V_address0");
    sc_trace(mVcdFile, data_1_V_ce0, "(port)data_1_V_ce0");
    sc_trace(mVcdFile, data_1_V_q0, "(port)data_1_V_q0");
    sc_trace(mVcdFile, data_2_V_address0, "(port)data_2_V_address0");
    sc_trace(mVcdFile, data_2_V_ce0, "(port)data_2_V_ce0");
    sc_trace(mVcdFile, data_2_V_q0, "(port)data_2_V_q0");
    sc_trace(mVcdFile, data_3_V_address0, "(port)data_3_V_address0");
    sc_trace(mVcdFile, data_3_V_ce0, "(port)data_3_V_ce0");
    sc_trace(mVcdFile, data_3_V_q0, "(port)data_3_V_q0");
    sc_trace(mVcdFile, data_4_V_address0, "(port)data_4_V_address0");
    sc_trace(mVcdFile, data_4_V_ce0, "(port)data_4_V_ce0");
    sc_trace(mVcdFile, data_4_V_q0, "(port)data_4_V_q0");
    sc_trace(mVcdFile, data_5_V_address0, "(port)data_5_V_address0");
    sc_trace(mVcdFile, data_5_V_ce0, "(port)data_5_V_ce0");
    sc_trace(mVcdFile, data_5_V_q0, "(port)data_5_V_q0");
    sc_trace(mVcdFile, data_6_V_address0, "(port)data_6_V_address0");
    sc_trace(mVcdFile, data_6_V_ce0, "(port)data_6_V_ce0");
    sc_trace(mVcdFile, data_6_V_q0, "(port)data_6_V_q0");
    sc_trace(mVcdFile, data_7_V_address0, "(port)data_7_V_address0");
    sc_trace(mVcdFile, data_7_V_ce0, "(port)data_7_V_ce0");
    sc_trace(mVcdFile, data_7_V_q0, "(port)data_7_V_q0");
    sc_trace(mVcdFile, res_0_V_address0, "(port)res_0_V_address0");
    sc_trace(mVcdFile, res_0_V_ce0, "(port)res_0_V_ce0");
    sc_trace(mVcdFile, res_0_V_we0, "(port)res_0_V_we0");
    sc_trace(mVcdFile, res_0_V_d0, "(port)res_0_V_d0");
    sc_trace(mVcdFile, res_1_V_address0, "(port)res_1_V_address0");
    sc_trace(mVcdFile, res_1_V_ce0, "(port)res_1_V_ce0");
    sc_trace(mVcdFile, res_1_V_we0, "(port)res_1_V_we0");
    sc_trace(mVcdFile, res_1_V_d0, "(port)res_1_V_d0");
    sc_trace(mVcdFile, res_2_V_address0, "(port)res_2_V_address0");
    sc_trace(mVcdFile, res_2_V_ce0, "(port)res_2_V_ce0");
    sc_trace(mVcdFile, res_2_V_we0, "(port)res_2_V_we0");
    sc_trace(mVcdFile, res_2_V_d0, "(port)res_2_V_d0");
    sc_trace(mVcdFile, res_3_V_address0, "(port)res_3_V_address0");
    sc_trace(mVcdFile, res_3_V_ce0, "(port)res_3_V_ce0");
    sc_trace(mVcdFile, res_3_V_we0, "(port)res_3_V_we0");
    sc_trace(mVcdFile, res_3_V_d0, "(port)res_3_V_d0");
    sc_trace(mVcdFile, res_4_V_address0, "(port)res_4_V_address0");
    sc_trace(mVcdFile, res_4_V_ce0, "(port)res_4_V_ce0");
    sc_trace(mVcdFile, res_4_V_we0, "(port)res_4_V_we0");
    sc_trace(mVcdFile, res_4_V_d0, "(port)res_4_V_d0");
    sc_trace(mVcdFile, res_5_V_address0, "(port)res_5_V_address0");
    sc_trace(mVcdFile, res_5_V_ce0, "(port)res_5_V_ce0");
    sc_trace(mVcdFile, res_5_V_we0, "(port)res_5_V_we0");
    sc_trace(mVcdFile, res_5_V_d0, "(port)res_5_V_d0");
    sc_trace(mVcdFile, res_6_V_address0, "(port)res_6_V_address0");
    sc_trace(mVcdFile, res_6_V_ce0, "(port)res_6_V_ce0");
    sc_trace(mVcdFile, res_6_V_we0, "(port)res_6_V_we0");
    sc_trace(mVcdFile, res_6_V_d0, "(port)res_6_V_d0");
    sc_trace(mVcdFile, res_7_V_address0, "(port)res_7_V_address0");
    sc_trace(mVcdFile, res_7_V_ce0, "(port)res_7_V_ce0");
    sc_trace(mVcdFile, res_7_V_we0, "(port)res_7_V_we0");
    sc_trace(mVcdFile, res_7_V_d0, "(port)res_7_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, w6_V_address0, "w6_V_address0");
    sc_trace(mVcdFile, w6_V_ce0, "w6_V_ce0");
    sc_trace(mVcdFile, w6_V_q0, "w6_V_q0");
    sc_trace(mVcdFile, b6_V_address0, "b6_V_address0");
    sc_trace(mVcdFile, b6_V_ce0, "b6_V_ce0");
    sc_trace(mVcdFile, b6_V_q0, "b6_V_q0");
    sc_trace(mVcdFile, acc_V_q0, "acc_V_q0");
    sc_trace(mVcdFile, reg_489, "reg_489");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, next_mul_fu_501_p2, "next_mul_fu_501_p2");
    sc_trace(mVcdFile, next_mul_reg_752, "next_mul_reg_752");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ii_7_fu_513_p2, "ii_7_fu_513_p2");
    sc_trace(mVcdFile, ii_7_reg_760, "ii_7_reg_760");
    sc_trace(mVcdFile, tmp_466_reg_765, "tmp_466_reg_765");
    sc_trace(mVcdFile, tmp_fu_507_p2, "tmp_fu_507_p2");
    sc_trace(mVcdFile, data_0_V_load_reg_810, "data_0_V_load_reg_810");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, data_1_V_load_reg_815, "data_1_V_load_reg_815");
    sc_trace(mVcdFile, data_2_V_load_reg_820, "data_2_V_load_reg_820");
    sc_trace(mVcdFile, data_3_V_load_reg_825, "data_3_V_load_reg_825");
    sc_trace(mVcdFile, data_4_V_load_reg_830, "data_4_V_load_reg_830");
    sc_trace(mVcdFile, data_5_V_load_reg_835, "data_5_V_load_reg_835");
    sc_trace(mVcdFile, data_6_V_load_reg_840, "data_6_V_load_reg_840");
    sc_trace(mVcdFile, data_7_V_load_reg_845, "data_7_V_load_reg_845");
    sc_trace(mVcdFile, tmp_227_fu_558_p3, "tmp_227_fu_558_p3");
    sc_trace(mVcdFile, tmp_227_reg_850, "tmp_227_reg_850");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, OP1_V_cast_fu_566_p1, "OP1_V_cast_fu_566_p1");
    sc_trace(mVcdFile, OP1_V_cast_reg_855, "OP1_V_cast_reg_855");
    sc_trace(mVcdFile, jj_3_fu_580_p2, "jj_3_fu_580_p2");
    sc_trace(mVcdFile, jj_3_reg_863, "jj_3_reg_863");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, index_fu_586_p2, "index_fu_586_p2");
    sc_trace(mVcdFile, index_reg_868, "index_reg_868");
    sc_trace(mVcdFile, tmp_230_fu_574_p2, "tmp_230_fu_574_p2");
    sc_trace(mVcdFile, idx_urem_fu_603_p3, "idx_urem_fu_603_p3");
    sc_trace(mVcdFile, tmp_233_fu_611_p1, "tmp_233_fu_611_p1");
    sc_trace(mVcdFile, tmp_233_reg_878, "tmp_233_reg_878");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, w6_V_load_reg_888, "w6_V_load_reg_888");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, grp_fu_747_p2, "grp_fu_747_p2");
    sc_trace(mVcdFile, p_Val2_s_reg_898, "p_Val2_s_reg_898");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, iacc_2_fu_634_p2, "iacc_2_fu_634_p2");
    sc_trace(mVcdFile, iacc_2_reg_906, "iacc_2_reg_906");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, tmp_229_fu_640_p1, "tmp_229_fu_640_p1");
    sc_trace(mVcdFile, tmp_229_reg_911, "tmp_229_reg_911");
    sc_trace(mVcdFile, tmp_s_fu_628_p2, "tmp_s_fu_628_p2");
    sc_trace(mVcdFile, b6_V_load_reg_921, "b6_V_load_reg_921");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ii_8_fu_655_p2, "ii_8_fu_655_p2");
    sc_trace(mVcdFile, ii_8_reg_929, "ii_8_reg_929");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, tmp_232_fu_661_p3, "tmp_232_fu_661_p3");
    sc_trace(mVcdFile, tmp_232_reg_934, "tmp_232_reg_934");
    sc_trace(mVcdFile, tmp_228_fu_649_p2, "tmp_228_fu_649_p2");
    sc_trace(mVcdFile, jj_4_fu_679_p2, "jj_4_fu_679_p2");
    sc_trace(mVcdFile, jj_4_reg_942, "jj_4_reg_942");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, index_2_fu_685_p2, "index_2_fu_685_p2");
    sc_trace(mVcdFile, index_2_reg_947, "index_2_reg_947");
    sc_trace(mVcdFile, tmp_237_fu_673_p2, "tmp_237_fu_673_p2");
    sc_trace(mVcdFile, acc_V_addr_4_reg_952, "acc_V_addr_4_reg_952");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, mult_V_q0, "mult_V_q0");
    sc_trace(mVcdFile, p_Val2_28_reg_962, "p_Val2_28_reg_962");
    sc_trace(mVcdFile, p_Val2_s_62_fu_699_p2, "p_Val2_s_62_fu_699_p2");
    sc_trace(mVcdFile, p_Val2_s_62_reg_967, "p_Val2_s_62_reg_967");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ires_2_fu_710_p2, "ires_2_fu_710_p2");
    sc_trace(mVcdFile, ires_2_reg_975, "ires_2_reg_975");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, tmp_231_fu_704_p2, "tmp_231_fu_704_p2");
    sc_trace(mVcdFile, arrayNo4_cast_reg_985, "arrayNo4_cast_reg_985");
    sc_trace(mVcdFile, res_0_V_addr_reg_989, "res_0_V_addr_reg_989");
    sc_trace(mVcdFile, res_1_V_addr_reg_994, "res_1_V_addr_reg_994");
    sc_trace(mVcdFile, res_2_V_addr_reg_999, "res_2_V_addr_reg_999");
    sc_trace(mVcdFile, res_3_V_addr_reg_1004, "res_3_V_addr_reg_1004");
    sc_trace(mVcdFile, res_4_V_addr_reg_1009, "res_4_V_addr_reg_1009");
    sc_trace(mVcdFile, res_5_V_addr_reg_1014, "res_5_V_addr_reg_1014");
    sc_trace(mVcdFile, res_6_V_addr_reg_1019, "res_6_V_addr_reg_1019");
    sc_trace(mVcdFile, res_7_V_addr_reg_1024, "res_7_V_addr_reg_1024");
    sc_trace(mVcdFile, mult_V_address0, "mult_V_address0");
    sc_trace(mVcdFile, mult_V_ce0, "mult_V_ce0");
    sc_trace(mVcdFile, mult_V_we0, "mult_V_we0");
    sc_trace(mVcdFile, mult_V_d0, "mult_V_d0");
    sc_trace(mVcdFile, acc_V_address0, "acc_V_address0");
    sc_trace(mVcdFile, acc_V_ce0, "acc_V_ce0");
    sc_trace(mVcdFile, acc_V_we0, "acc_V_we0");
    sc_trace(mVcdFile, acc_V_d0, "acc_V_d0");
    sc_trace(mVcdFile, ii_reg_398, "ii_reg_398");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, phi_mul_reg_410, "phi_mul_reg_410");
    sc_trace(mVcdFile, phi_urem_reg_421, "phi_urem_reg_421");
    sc_trace(mVcdFile, jj_reg_433, "jj_reg_433");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, iacc_reg_444, "iacc_reg_444");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ii2_reg_455, "ii2_reg_455");
    sc_trace(mVcdFile, jj3_reg_466, "jj3_reg_466");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, ires_reg_477, "ires_reg_477");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, newIndex7_fu_529_p1, "newIndex7_fu_529_p1");
    sc_trace(mVcdFile, tmp_238_fu_690_p1, "tmp_238_fu_690_p1");
    sc_trace(mVcdFile, tmp_239_fu_695_p1, "tmp_239_fu_695_p1");
    sc_trace(mVcdFile, tmp_236_fu_716_p1, "tmp_236_fu_716_p1");
    sc_trace(mVcdFile, newIndex8_fu_735_p1, "newIndex8_fu_735_p1");
    sc_trace(mVcdFile, b6_V_load_cast_fu_645_p1, "b6_V_load_cast_fu_645_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, cache_V_fu_544_p9, "cache_V_fu_544_p9");
    sc_trace(mVcdFile, cache_V_fu_544_p10, "cache_V_fu_544_p10");
    sc_trace(mVcdFile, jj_cast_fu_570_p1, "jj_cast_fu_570_p1");
    sc_trace(mVcdFile, next_urem_fu_591_p2, "next_urem_fu_591_p2");
    sc_trace(mVcdFile, tmp_467_fu_597_p2, "tmp_467_fu_597_p2");
    sc_trace(mVcdFile, jj3_cast_fu_669_p1, "jj3_cast_fu_669_p1");
    sc_trace(mVcdFile, tmp_468_fu_731_p1, "tmp_468_fu_731_p1");
    sc_trace(mVcdFile, grp_fu_747_p0, "grp_fu_747_p0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::~dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete w6_V_U;
    delete b6_V_U;
    delete mult_V_U;
    delete acc_V_U;
    delete myproject_mux_832_16_1_1_U594;
    delete myproject_mul_mul_16s_11s_26_3_1_U595;
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(tmp_231_fu_704_p2.read(), ap_const_lv1_1) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_fu_507_p2.read(), ap_const_lv1_1))) {
        iacc_reg_444 = ap_const_lv8_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        iacc_reg_444 = iacc_2_reg_906.read();
    }
    if ((esl_seteq<1,1,1>(tmp_s_fu_628_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        ii2_reg_455 = ap_const_lv13_0;
    } else if ((esl_seteq<1,1,1>(tmp_237_fu_673_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        ii2_reg_455 = ii_8_reg_929.read();
    }
    if ((!(esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ii_reg_398 = ap_const_lv13_0;
    } else if ((esl_seteq<1,1,1>(tmp_230_fu_574_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        ii_reg_398 = ii_7_reg_760.read();
    }
    if ((esl_seteq<1,1,1>(tmp_228_fu_649_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        ires_reg_477 = ap_const_lv8_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        ires_reg_477 = ires_2_reg_975.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        jj3_reg_466 = jj_4_reg_942.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                esl_seteq<1,1,1>(tmp_228_fu_649_p2.read(), ap_const_lv1_0))) {
        jj3_reg_466 = ap_const_lv8_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        jj_reg_433 = jj_3_reg_863.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        jj_reg_433 = ap_const_lv8_0;
    }
    if ((!(esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        phi_mul_reg_410 = ap_const_lv27_0;
    } else if ((esl_seteq<1,1,1>(tmp_230_fu_574_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        phi_mul_reg_410 = next_mul_reg_752.read();
    }
    if ((!(esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        phi_urem_reg_421 = ap_const_lv13_0;
    } else if ((esl_seteq<1,1,1>(tmp_230_fu_574_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        phi_urem_reg_421 = idx_urem_fu_603_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        OP1_V_cast_reg_855 = OP1_V_cast_fu_566_p1.read();
        tmp_227_reg_850 = tmp_227_fu_558_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(tmp_237_fu_673_p2.read(), ap_const_lv1_0))) {
        acc_V_addr_4_reg_952 =  (sc_lv<7>) (tmp_238_fu_690_p1.read());
        index_2_reg_947 = index_2_fu_685_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        arrayNo4_cast_reg_985 = ires_reg_477.read().range(7, 4);
        res_0_V_addr_reg_989 =  (sc_lv<4>) (newIndex8_fu_735_p1.read());
        res_1_V_addr_reg_994 =  (sc_lv<4>) (newIndex8_fu_735_p1.read());
        res_2_V_addr_reg_999 =  (sc_lv<4>) (newIndex8_fu_735_p1.read());
        res_3_V_addr_reg_1004 =  (sc_lv<4>) (newIndex8_fu_735_p1.read());
        res_4_V_addr_reg_1009 =  (sc_lv<4>) (newIndex8_fu_735_p1.read());
        res_5_V_addr_reg_1014 =  (sc_lv<4>) (newIndex8_fu_735_p1.read());
        res_6_V_addr_reg_1019 =  (sc_lv<4>) (newIndex8_fu_735_p1.read());
        res_7_V_addr_reg_1024 =  (sc_lv<4>) (newIndex8_fu_735_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        b6_V_load_reg_921 = b6_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        data_0_V_load_reg_810 = data_0_V_q0.read();
        data_1_V_load_reg_815 = data_1_V_q0.read();
        data_2_V_load_reg_820 = data_2_V_q0.read();
        data_3_V_load_reg_825 = data_3_V_q0.read();
        data_4_V_load_reg_830 = data_4_V_q0.read();
        data_5_V_load_reg_835 = data_5_V_q0.read();
        data_6_V_load_reg_840 = data_6_V_q0.read();
        data_7_V_load_reg_845 = data_7_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        iacc_2_reg_906 = iacc_2_fu_634_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        ii_7_reg_760 = ii_7_fu_513_p2.read();
        next_mul_reg_752 = next_mul_fu_501_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        ii_8_reg_929 = ii_8_fu_655_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(tmp_230_fu_574_p2.read(), ap_const_lv1_0))) {
        index_reg_868 = index_fu_586_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        ires_2_reg_975 = ires_2_fu_710_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        jj_3_reg_863 = jj_3_fu_580_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        jj_4_reg_942 = jj_4_fu_679_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        p_Val2_28_reg_962 = mult_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        p_Val2_s_62_reg_967 = p_Val2_s_62_fu_699_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        p_Val2_s_reg_898 = grp_fu_747_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()))) {
        reg_489 = acc_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(tmp_s_fu_628_p2.read(), ap_const_lv1_0))) {
        tmp_229_reg_911 = tmp_229_fu_640_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(tmp_228_fu_649_p2.read(), ap_const_lv1_0))) {
        tmp_232_reg_934 = tmp_232_fu_661_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        tmp_233_reg_878 = tmp_233_fu_611_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_fu_507_p2.read(), ap_const_lv1_0))) {
        tmp_466_reg_765 = phi_mul_reg_410.read().range(26, 23);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        w6_V_load_reg_888 = w6_V_q0.read();
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_OP1_V_cast_fu_566_p1() {
    OP1_V_cast_fu_566_p1 = esl_sext<26,16>(cache_V_fu_544_p10.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_acc_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        acc_V_address0 =  (sc_lv<7>) (tmp_236_fu_716_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        acc_V_address0 = acc_V_addr_4_reg_952.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        acc_V_address0 =  (sc_lv<7>) (tmp_229_reg_911.read());
    } else {
        acc_V_address0 = "XXXXXXX";
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_acc_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        acc_V_ce0 = ap_const_logic_1;
    } else {
        acc_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_acc_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        acc_V_d0 = p_Val2_s_62_reg_967.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        acc_V_d0 = b6_V_load_cast_fu_645_p1.read();
    } else {
        acc_V_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_acc_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        acc_V_we0 = ap_const_logic_1;
    } else {
        acc_V_we0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(tmp_231_fu_704_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(tmp_231_fu_704_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_b6_V_address0() {
    b6_V_address0 =  (sc_lv<7>) (tmp_229_fu_640_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_b6_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        b6_V_ce0 = ap_const_logic_1;
    } else {
        b6_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_b6_V_load_cast_fu_645_p1() {
    b6_V_load_cast_fu_645_p1 = esl_sext<16,10>(b6_V_load_reg_921.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_cache_V_fu_544_p9() {
    cache_V_fu_544_p9 = esl_zext<32,4>(tmp_466_reg_765.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_data_0_V_address0() {
    data_0_V_address0 =  (sc_lv<10>) (newIndex7_fu_529_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_data_0_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_0_V_ce0 = ap_const_logic_1;
    } else {
        data_0_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_data_1_V_address0() {
    data_1_V_address0 =  (sc_lv<10>) (newIndex7_fu_529_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_data_1_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_1_V_ce0 = ap_const_logic_1;
    } else {
        data_1_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_data_2_V_address0() {
    data_2_V_address0 =  (sc_lv<10>) (newIndex7_fu_529_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_data_2_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_2_V_ce0 = ap_const_logic_1;
    } else {
        data_2_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_data_3_V_address0() {
    data_3_V_address0 =  (sc_lv<10>) (newIndex7_fu_529_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_data_3_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_3_V_ce0 = ap_const_logic_1;
    } else {
        data_3_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_data_4_V_address0() {
    data_4_V_address0 =  (sc_lv<10>) (newIndex7_fu_529_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_data_4_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_4_V_ce0 = ap_const_logic_1;
    } else {
        data_4_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_data_5_V_address0() {
    data_5_V_address0 =  (sc_lv<10>) (newIndex7_fu_529_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_data_5_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_5_V_ce0 = ap_const_logic_1;
    } else {
        data_5_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_data_6_V_address0() {
    data_6_V_address0 =  (sc_lv<10>) (newIndex7_fu_529_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_data_6_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_6_V_ce0 = ap_const_logic_1;
    } else {
        data_6_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_data_7_V_address0() {
    data_7_V_address0 =  (sc_lv<10>) (newIndex7_fu_529_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_data_7_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_7_V_ce0 = ap_const_logic_1;
    } else {
        data_7_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_grp_fu_747_p0() {
    grp_fu_747_p0 =  (sc_lv<16>) (OP1_V_cast_reg_855.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_iacc_2_fu_634_p2() {
    iacc_2_fu_634_p2 = (!iacc_reg_444.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(iacc_reg_444.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_idx_urem_fu_603_p3() {
    idx_urem_fu_603_p3 = (!tmp_467_fu_597_p2.read()[0].is_01())? sc_lv<13>(): ((tmp_467_fu_597_p2.read()[0].to_bool())? next_urem_fu_591_p2.read(): ap_const_lv13_0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ii_7_fu_513_p2() {
    ii_7_fu_513_p2 = (!ii_reg_398.read().is_01() || !ap_const_lv13_1.is_01())? sc_lv<13>(): (sc_biguint<13>(ii_reg_398.read()) + sc_biguint<13>(ap_const_lv13_1));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ii_8_fu_655_p2() {
    ii_8_fu_655_p2 = (!ii2_reg_455.read().is_01() || !ap_const_lv13_1.is_01())? sc_lv<13>(): (sc_biguint<13>(ii2_reg_455.read()) + sc_biguint<13>(ap_const_lv13_1));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_index_2_fu_685_p2() {
    index_2_fu_685_p2 = (!tmp_232_reg_934.read().is_01() || !jj3_cast_fu_669_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(tmp_232_reg_934.read()) + sc_biguint<20>(jj3_cast_fu_669_p1.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_index_fu_586_p2() {
    index_fu_586_p2 = (!tmp_227_reg_850.read().is_01() || !jj_cast_fu_570_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(tmp_227_reg_850.read()) + sc_biguint<20>(jj_cast_fu_570_p1.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ires_2_fu_710_p2() {
    ires_2_fu_710_p2 = (!ires_reg_477.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(ires_reg_477.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_jj3_cast_fu_669_p1() {
    jj3_cast_fu_669_p1 = esl_zext<20,8>(jj3_reg_466.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_jj_3_fu_580_p2() {
    jj_3_fu_580_p2 = (!jj_reg_433.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(jj_reg_433.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_jj_4_fu_679_p2() {
    jj_4_fu_679_p2 = (!jj3_reg_466.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(jj3_reg_466.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_jj_cast_fu_570_p1() {
    jj_cast_fu_570_p1 = esl_zext<20,8>(jj_reg_433.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_mult_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        mult_V_address0 =  (sc_lv<20>) (tmp_239_fu_695_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        mult_V_address0 =  (sc_lv<20>) (tmp_233_reg_878.read());
    } else {
        mult_V_address0 =  (sc_lv<20>) ("XXXXXXXXXXXXXXXXXXXX");
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_mult_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        mult_V_ce0 = ap_const_logic_1;
    } else {
        mult_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_mult_V_d0() {
    mult_V_d0 = p_Val2_s_reg_898.read().range(25, 10);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_mult_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        mult_V_we0 = ap_const_logic_1;
    } else {
        mult_V_we0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_newIndex7_fu_529_p1() {
    newIndex7_fu_529_p1 = esl_zext<64,13>(phi_urem_reg_421.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_newIndex8_fu_735_p1() {
    newIndex8_fu_735_p1 = esl_zext<64,4>(tmp_468_fu_731_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_next_mul_fu_501_p2() {
    next_mul_fu_501_p2 = (!phi_mul_reg_410.read().is_01() || !ap_const_lv27_2E8C.is_01())? sc_lv<27>(): (sc_biguint<27>(phi_mul_reg_410.read()) + sc_biguint<27>(ap_const_lv27_2E8C));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_next_urem_fu_591_p2() {
    next_urem_fu_591_p2 = (!phi_urem_reg_421.read().is_01() || !ap_const_lv13_1.is_01())? sc_lv<13>(): (sc_biguint<13>(phi_urem_reg_421.read()) + sc_biguint<13>(ap_const_lv13_1));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_p_Val2_s_62_fu_699_p2() {
    p_Val2_s_62_fu_699_p2 = (!reg_489.read().is_01() || !p_Val2_28_reg_962.read().is_01())? sc_lv<16>(): (sc_biguint<16>(reg_489.read()) + sc_biguint<16>(p_Val2_28_reg_962.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_0_V_address0() {
    res_0_V_address0 = res_0_V_addr_reg_989.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_0_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        res_0_V_ce0 = ap_const_logic_1;
    } else {
        res_0_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_0_V_d0() {
    res_0_V_d0 = reg_489.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_0_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) && 
         esl_seteq<1,4,4>(arrayNo4_cast_reg_985.read(), ap_const_lv4_0))) {
        res_0_V_we0 = ap_const_logic_1;
    } else {
        res_0_V_we0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_1_V_address0() {
    res_1_V_address0 = res_1_V_addr_reg_994.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_1_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        res_1_V_ce0 = ap_const_logic_1;
    } else {
        res_1_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_1_V_d0() {
    res_1_V_d0 = reg_489.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_1_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) && 
         esl_seteq<1,4,4>(arrayNo4_cast_reg_985.read(), ap_const_lv4_1))) {
        res_1_V_we0 = ap_const_logic_1;
    } else {
        res_1_V_we0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_2_V_address0() {
    res_2_V_address0 = res_2_V_addr_reg_999.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_2_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        res_2_V_ce0 = ap_const_logic_1;
    } else {
        res_2_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_2_V_d0() {
    res_2_V_d0 = reg_489.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_2_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) && 
         esl_seteq<1,4,4>(arrayNo4_cast_reg_985.read(), ap_const_lv4_2))) {
        res_2_V_we0 = ap_const_logic_1;
    } else {
        res_2_V_we0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_3_V_address0() {
    res_3_V_address0 = res_3_V_addr_reg_1004.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_3_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        res_3_V_ce0 = ap_const_logic_1;
    } else {
        res_3_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_3_V_d0() {
    res_3_V_d0 = reg_489.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_3_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) && 
         esl_seteq<1,4,4>(arrayNo4_cast_reg_985.read(), ap_const_lv4_3))) {
        res_3_V_we0 = ap_const_logic_1;
    } else {
        res_3_V_we0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_4_V_address0() {
    res_4_V_address0 = res_4_V_addr_reg_1009.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_4_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        res_4_V_ce0 = ap_const_logic_1;
    } else {
        res_4_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_4_V_d0() {
    res_4_V_d0 = reg_489.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_4_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) && 
         esl_seteq<1,4,4>(arrayNo4_cast_reg_985.read(), ap_const_lv4_4))) {
        res_4_V_we0 = ap_const_logic_1;
    } else {
        res_4_V_we0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_5_V_address0() {
    res_5_V_address0 = res_5_V_addr_reg_1014.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_5_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        res_5_V_ce0 = ap_const_logic_1;
    } else {
        res_5_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_5_V_d0() {
    res_5_V_d0 = reg_489.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_5_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) && 
         esl_seteq<1,4,4>(arrayNo4_cast_reg_985.read(), ap_const_lv4_5))) {
        res_5_V_we0 = ap_const_logic_1;
    } else {
        res_5_V_we0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_6_V_address0() {
    res_6_V_address0 = res_6_V_addr_reg_1019.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_6_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        res_6_V_ce0 = ap_const_logic_1;
    } else {
        res_6_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_6_V_d0() {
    res_6_V_d0 = reg_489.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_6_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) && 
         esl_seteq<1,4,4>(arrayNo4_cast_reg_985.read(), ap_const_lv4_6))) {
        res_6_V_we0 = ap_const_logic_1;
    } else {
        res_6_V_we0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_7_V_address0() {
    res_7_V_address0 = res_7_V_addr_reg_1024.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_7_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        res_7_V_ce0 = ap_const_logic_1;
    } else {
        res_7_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_7_V_d0() {
    res_7_V_d0 = reg_489.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_res_7_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) && 
         !esl_seteq<1,4,4>(arrayNo4_cast_reg_985.read(), ap_const_lv4_0) && 
         !esl_seteq<1,4,4>(arrayNo4_cast_reg_985.read(), ap_const_lv4_1) && 
         !esl_seteq<1,4,4>(arrayNo4_cast_reg_985.read(), ap_const_lv4_2) && 
         !esl_seteq<1,4,4>(arrayNo4_cast_reg_985.read(), ap_const_lv4_3) && 
         !esl_seteq<1,4,4>(arrayNo4_cast_reg_985.read(), ap_const_lv4_4) && 
         !esl_seteq<1,4,4>(arrayNo4_cast_reg_985.read(), ap_const_lv4_5) && 
         !esl_seteq<1,4,4>(arrayNo4_cast_reg_985.read(), ap_const_lv4_6))) {
        res_7_V_we0 = ap_const_logic_1;
    } else {
        res_7_V_we0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_tmp_227_fu_558_p3() {
    tmp_227_fu_558_p3 = esl_concat<13,7>(ii_reg_398.read(), ap_const_lv7_0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_tmp_228_fu_649_p2() {
    tmp_228_fu_649_p2 = (!ii2_reg_455.read().is_01() || !ap_const_lv13_1600.is_01())? sc_lv<1>(): sc_lv<1>(ii2_reg_455.read() == ap_const_lv13_1600);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_tmp_229_fu_640_p1() {
    tmp_229_fu_640_p1 = esl_zext<64,8>(iacc_reg_444.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_tmp_230_fu_574_p2() {
    tmp_230_fu_574_p2 = (!jj_reg_433.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(jj_reg_433.read() == ap_const_lv8_80);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_tmp_231_fu_704_p2() {
    tmp_231_fu_704_p2 = (!ires_reg_477.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(ires_reg_477.read() == ap_const_lv8_80);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_tmp_232_fu_661_p3() {
    tmp_232_fu_661_p3 = esl_concat<13,7>(ii2_reg_455.read(), ap_const_lv7_0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_tmp_233_fu_611_p1() {
    tmp_233_fu_611_p1 = esl_zext<64,20>(index_reg_868.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_tmp_236_fu_716_p1() {
    tmp_236_fu_716_p1 = esl_zext<64,8>(ires_reg_477.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_tmp_237_fu_673_p2() {
    tmp_237_fu_673_p2 = (!jj3_reg_466.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(jj3_reg_466.read() == ap_const_lv8_80);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_tmp_238_fu_690_p1() {
    tmp_238_fu_690_p1 = esl_zext<64,8>(jj3_reg_466.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_tmp_239_fu_695_p1() {
    tmp_239_fu_695_p1 = esl_zext<64,20>(index_2_reg_947.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_tmp_467_fu_597_p2() {
    tmp_467_fu_597_p2 = (!next_urem_fu_591_p2.read().is_01() || !ap_const_lv13_2C0.is_01())? sc_lv<1>(): (sc_biguint<13>(next_urem_fu_591_p2.read()) < sc_biguint<13>(ap_const_lv13_2C0));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_tmp_468_fu_731_p1() {
    tmp_468_fu_731_p1 = ires_reg_477.read().range(4-1, 0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_tmp_fu_507_p2() {
    tmp_fu_507_p2 = (!ii_reg_398.read().is_01() || !ap_const_lv13_1600.is_01())? sc_lv<1>(): sc_lv<1>(ii_reg_398.read() == ap_const_lv13_1600);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_tmp_s_fu_628_p2() {
    tmp_s_fu_628_p2 = (!iacc_reg_444.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(iacc_reg_444.read() == ap_const_lv8_80);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_w6_V_address0() {
    w6_V_address0 =  (sc_lv<20>) (tmp_233_fu_611_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_w6_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        w6_V_ce0 = ap_const_logic_1;
    } else {
        w6_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_fu_507_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(tmp_230_fu_574_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(tmp_s_fu_628_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 16384 : 
            if ((esl_seteq<1,1,1>(tmp_228_fu_649_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
                ap_NS_fsm = ap_ST_fsm_state21;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        case 32768 : 
            if ((esl_seteq<1,1,1>(tmp_237_fu_673_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_state17;
            }
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 1048576 : 
            if ((esl_seteq<1,1,1>(tmp_231_fu_704_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state22;
            }
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<24>) ("XXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

