// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state1 = "1";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state2 = "10";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state3 = "100";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state4 = "1000";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state5 = "10000";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state6 = "100000";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state7 = "1000000";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state8 = "10000000";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state9 = "100000000";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state10 = "1000000000";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state11 = "10000000000";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state12 = "100000000000";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<20> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_1 = "1";
const sc_lv<1> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv1_0 = "0";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_2 = "10";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_3 = "11";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_4 = "100";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_5 = "101";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_6 = "110";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_8 = "1000";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_A = "1010";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_B = "1011";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_D = "1101";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_E = "1110";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_F = "1111";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_10 = "10000";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_12 = "10010";
const sc_lv<1> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv1_1 = "1";
const sc_lv<8> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv8_0 = "00000000";
const sc_lv<3> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv3_0 = "000";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_9 = "1001";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_C = "1100";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_11 = "10001";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_13 = "10011";
const sc_lv<2> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv2_1 = "1";
const sc_lv<2> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv2_0 = "00";
const sc_lv<8> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv8_80 = "10000000";
const sc_lv<8> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv8_1 = "1";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_7 = "111";
const sc_lv<3> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv3_6 = "110";
const sc_lv<3> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv3_1 = "1";
const sc_lv<32> dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_lv32_19 = "11001";
const bool dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::ap_const_boolean_1 = true;

dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    w10_V_U = new dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s_w10_V("w10_V_U");
    w10_V_U->clk(ap_clk);
    w10_V_U->reset(ap_rst);
    w10_V_U->address0(w10_V_address0);
    w10_V_U->ce0(w10_V_ce0);
    w10_V_U->q0(w10_V_q0);
    b10_V_U = new dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s_b10_V("b10_V_U");
    b10_V_U->clk(ap_clk);
    b10_V_U->reset(ap_rst);
    b10_V_U->address0(b10_V_address0);
    b10_V_U->ce0(b10_V_ce0);
    b10_V_U->q0(b10_V_q0);
    mult_V_U = new dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s_mult_V("mult_V_U");
    mult_V_U->clk(ap_clk);
    mult_V_U->reset(ap_rst);
    mult_V_U->address0(mult_V_address0);
    mult_V_U->ce0(mult_V_ce0);
    mult_V_U->we0(mult_V_we0);
    mult_V_U->d0(mult_V_d0);
    mult_V_U->q0(mult_V_q0);
    acc_V_U = new dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s_acc_V("acc_V_U");
    acc_V_U->clk(ap_clk);
    acc_V_U->reset(ap_rst);
    acc_V_U->address0(acc_V_address0);
    acc_V_U->ce0(acc_V_ce0);
    acc_V_U->we0(acc_V_we0);
    acc_V_U->d0(acc_V_d0);
    acc_V_U->q0(acc_V_q0);
    myproject_mux_832_16_1_1_U672 = new myproject_mux_832_16_1_1<1,1,16,16,16,16,16,16,16,16,32,16>("myproject_mux_832_16_1_1_U672");
    myproject_mux_832_16_1_1_U672->din0(cache_V_fu_460_p1);
    myproject_mux_832_16_1_1_U672->din1(cache_V_fu_460_p2);
    myproject_mux_832_16_1_1_U672->din2(cache_V_fu_460_p3);
    myproject_mux_832_16_1_1_U672->din3(cache_V_fu_460_p4);
    myproject_mux_832_16_1_1_U672->din4(cache_V_fu_460_p5);
    myproject_mux_832_16_1_1_U672->din5(cache_V_fu_460_p6);
    myproject_mux_832_16_1_1_U672->din6(cache_V_fu_460_p7);
    myproject_mux_832_16_1_1_U672->din7(cache_V_fu_460_p8);
    myproject_mux_832_16_1_1_U672->din8(cache_V_fu_460_p9);
    myproject_mux_832_16_1_1_U672->dout(cache_V_fu_460_p10);
    myproject_mul_mul_16s_12s_26_3_1_U673 = new myproject_mul_mul_16s_12s_26_3_1<1,3,16,12,26>("myproject_mul_mul_16s_12s_26_3_1_U673");
    myproject_mul_mul_16s_12s_26_3_1_U673->clk(ap_clk);
    myproject_mul_mul_16s_12s_26_3_1_U673->reset(ap_rst);
    myproject_mul_mul_16s_12s_26_3_1_U673->din0(grp_fu_702_p0);
    myproject_mul_mul_16s_12s_26_3_1_U673->din1(w10_V_load_reg_788);
    myproject_mul_mul_16s_12s_26_3_1_U673->ce(ap_var_for_const0);
    myproject_mul_mul_16s_12s_26_3_1_U673->dout(grp_fu_702_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_OP1_V_cast_fu_514_p1);
    sensitive << ( cache_V_fu_460_p10 );

    SC_METHOD(thread_acc_V_address0);
    sensitive << ( tmp_242_reg_811 );
    sensitive << ( acc_V_addr_6_reg_852 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( tmp_251_fu_649_p1 );
    sensitive << ( tmp_249_fu_676_p1 );

    SC_METHOD(thread_acc_V_ce0);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_acc_V_d0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( b10_V_load_cast_fu_577_p1 );
    sensitive << ( p_Val2_s_70_fu_659_p2 );

    SC_METHOD(thread_acc_V_we0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( tmp_244_fu_664_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( tmp_244_fu_664_p2 );

    SC_METHOD(thread_arrayNo5_cast_fu_681_p4);
    sensitive << ( ires_reg_374 );

    SC_METHOD(thread_arrayNo_fu_414_p4);
    sensitive << ( ii_reg_317 );

    SC_METHOD(thread_b10_V_address0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( tmp_242_fu_572_p1 );

    SC_METHOD(thread_b10_V_ce0);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_b10_V_load_cast_fu_577_p1);
    sensitive << ( b10_V_load_reg_821 );

    SC_METHOD(thread_cache_V_fu_460_p1);
    sensitive << ( data_0_V_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_cache_V_fu_460_p2);
    sensitive << ( data_1_V_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_cache_V_fu_460_p3);
    sensitive << ( data_2_V_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_cache_V_fu_460_p4);
    sensitive << ( data_3_V_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_cache_V_fu_460_p5);
    sensitive << ( data_4_V_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_cache_V_fu_460_p6);
    sensitive << ( data_5_V_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_cache_V_fu_460_p7);
    sensitive << ( data_6_V_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_cache_V_fu_460_p8);
    sensitive << ( data_7_V_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_cache_V_fu_460_p9);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( arrayNo_fu_414_p4 );

    SC_METHOD(thread_data_0_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( newIndex_fu_402_p1 );

    SC_METHOD(thread_data_0_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_data_1_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( newIndex_fu_402_p1 );

    SC_METHOD(thread_data_1_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_data_2_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( newIndex_fu_402_p1 );

    SC_METHOD(thread_data_2_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_data_3_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( newIndex_fu_402_p1 );

    SC_METHOD(thread_data_3_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_data_4_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( newIndex_fu_402_p1 );

    SC_METHOD(thread_data_4_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_data_5_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( newIndex_fu_402_p1 );

    SC_METHOD(thread_data_5_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_data_6_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( newIndex_fu_402_p1 );

    SC_METHOD(thread_data_6_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_data_7_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( newIndex_fu_402_p1 );

    SC_METHOD(thread_data_7_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_grp_fu_702_p0);
    sensitive << ( OP1_V_cast_reg_760 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_iacc_3_fu_566_p2);
    sensitive << ( iacc_reg_340 );

    SC_METHOD(thread_ii_10_fu_587_p2);
    sensitive << ( ii2_reg_351 );

    SC_METHOD(thread_ii_9_fu_392_p2);
    sensitive << ( ii_reg_317 );

    SC_METHOD(thread_index_3_cast_fu_646_p1);
    sensitive << ( index_3_reg_847 );

    SC_METHOD(thread_index_3_fu_641_p2);
    sensitive << ( tmp_245_reg_834 );
    sensitive << ( jj3_cast3_fu_625_p1 );

    SC_METHOD(thread_index_cast_fu_539_p1);
    sensitive << ( index_reg_773 );

    SC_METHOD(thread_index_fu_534_p2);
    sensitive << ( tmp_240_reg_755 );
    sensitive << ( jj_cast6_fu_518_p1 );

    SC_METHOD(thread_ires_3_fu_670_p2);
    sensitive << ( ires_reg_374 );

    SC_METHOD(thread_jj3_cast3_fu_625_p1);
    sensitive << ( jj3_reg_362 );

    SC_METHOD(thread_jj_5_fu_528_p2);
    sensitive << ( jj_reg_329 );

    SC_METHOD(thread_jj_6_fu_635_p2);
    sensitive << ( jj3_reg_362 );

    SC_METHOD(thread_jj_cast6_fu_518_p1);
    sensitive << ( jj_reg_329 );

    SC_METHOD(thread_mult_V_address0);
    sensitive << ( tmp_246_reg_778 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_252_fu_654_p1 );

    SC_METHOD(thread_mult_V_ce0);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_mult_V_d0);
    sensitive << ( p_Val2_s_reg_798 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_mult_V_we0);
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_newIndex9_fu_695_p1);
    sensitive << ( tmp_474_fu_691_p1 );

    SC_METHOD(thread_newIndex_fu_402_p1);
    sensitive << ( tmp_469_fu_398_p1 );

    SC_METHOD(thread_p_Val2_s_70_fu_659_p2);
    sensitive << ( p_Val2_29_reg_862 );
    sensitive << ( p_Val2_30_reg_867 );

    SC_METHOD(thread_p_shl7_cast_fu_504_p1);
    sensitive << ( tmp_471_fu_498_p2 );

    SC_METHOD(thread_p_shl8_cast_fu_605_p1);
    sensitive << ( p_shl8_fu_597_p3 );

    SC_METHOD(thread_p_shl8_fu_597_p3);
    sensitive << ( tmp_472_fu_593_p1 );

    SC_METHOD(thread_p_shl9_cast_fu_615_p1);
    sensitive << ( tmp_473_fu_609_p2 );

    SC_METHOD(thread_p_shl_cast_fu_494_p1);
    sensitive << ( p_shl_fu_486_p3 );

    SC_METHOD(thread_p_shl_fu_486_p3);
    sensitive << ( tmp_470_fu_482_p1 );

    SC_METHOD(thread_res_0_V_address0);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( newIndex9_fu_695_p1 );

    SC_METHOD(thread_res_0_V_ce0);
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_res_0_V_d0);
    sensitive << ( acc_V_q0 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_res_0_V_we0);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( arrayNo5_cast_fu_681_p4 );

    SC_METHOD(thread_res_1_V_address0);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( newIndex9_fu_695_p1 );

    SC_METHOD(thread_res_1_V_ce0);
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_res_1_V_d0);
    sensitive << ( acc_V_q0 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_res_1_V_we0);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( arrayNo5_cast_fu_681_p4 );

    SC_METHOD(thread_res_2_V_address0);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( newIndex9_fu_695_p1 );

    SC_METHOD(thread_res_2_V_ce0);
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_res_2_V_d0);
    sensitive << ( acc_V_q0 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_res_2_V_we0);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( arrayNo5_cast_fu_681_p4 );

    SC_METHOD(thread_tmp_240_fu_508_p2);
    sensitive << ( p_shl_cast_fu_494_p1 );
    sensitive << ( p_shl7_cast_fu_504_p1 );

    SC_METHOD(thread_tmp_241_fu_581_p2);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ii2_reg_351 );

    SC_METHOD(thread_tmp_242_fu_572_p1);
    sensitive << ( iacc_reg_340 );

    SC_METHOD(thread_tmp_243_fu_522_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( jj_reg_329 );

    SC_METHOD(thread_tmp_244_fu_664_p2);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ires_reg_374 );

    SC_METHOD(thread_tmp_245_fu_619_p2);
    sensitive << ( p_shl8_cast_fu_605_p1 );
    sensitive << ( p_shl9_cast_fu_615_p1 );

    SC_METHOD(thread_tmp_246_fu_542_p1);
    sensitive << ( index_cast_fu_539_p1 );

    SC_METHOD(thread_tmp_249_fu_676_p1);
    sensitive << ( ires_reg_374 );

    SC_METHOD(thread_tmp_250_fu_629_p2);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( jj3_reg_362 );

    SC_METHOD(thread_tmp_251_fu_649_p1);
    sensitive << ( jj3_reg_362 );

    SC_METHOD(thread_tmp_252_fu_654_p1);
    sensitive << ( index_3_cast_fu_646_p1 );

    SC_METHOD(thread_tmp_469_fu_398_p1);
    sensitive << ( ii_reg_317 );

    SC_METHOD(thread_tmp_470_fu_482_p1);
    sensitive << ( ii_reg_317 );

    SC_METHOD(thread_tmp_471_fu_498_p2);
    sensitive << ( ii_reg_317 );

    SC_METHOD(thread_tmp_472_fu_593_p1);
    sensitive << ( ii2_reg_351 );

    SC_METHOD(thread_tmp_473_fu_609_p2);
    sensitive << ( ii2_reg_351 );

    SC_METHOD(thread_tmp_474_fu_691_p1);
    sensitive << ( ires_reg_374 );

    SC_METHOD(thread_tmp_fu_386_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ii_reg_317 );

    SC_METHOD(thread_tmp_s_fu_560_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( iacc_reg_340 );

    SC_METHOD(thread_w10_V_address0);
    sensitive << ( tmp_246_fu_542_p1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_w10_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_386_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_243_fu_522_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( tmp_s_fu_560_p2 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( tmp_241_fu_581_p2 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( tmp_250_fu_629_p2 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( tmp_244_fu_664_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_address0, "(port)data_0_V_address0");
    sc_trace(mVcdFile, data_0_V_ce0, "(port)data_0_V_ce0");
    sc_trace(mVcdFile, data_0_V_q0, "(port)data_0_V_q0");
    sc_trace(mVcdFile, data_1_V_address0, "(port)data_1_V_address0");
    sc_trace(mVcdFile, data_1_V_ce0, "(port)data_1_V_ce0");
    sc_trace(mVcdFile, data_1_V_q0, "(port)data_1_V_q0");
    sc_trace(mVcdFile, data_2_V_address0, "(port)data_2_V_address0");
    sc_trace(mVcdFile, data_2_V_ce0, "(port)data_2_V_ce0");
    sc_trace(mVcdFile, data_2_V_q0, "(port)data_2_V_q0");
    sc_trace(mVcdFile, data_3_V_address0, "(port)data_3_V_address0");
    sc_trace(mVcdFile, data_3_V_ce0, "(port)data_3_V_ce0");
    sc_trace(mVcdFile, data_3_V_q0, "(port)data_3_V_q0");
    sc_trace(mVcdFile, data_4_V_address0, "(port)data_4_V_address0");
    sc_trace(mVcdFile, data_4_V_ce0, "(port)data_4_V_ce0");
    sc_trace(mVcdFile, data_4_V_q0, "(port)data_4_V_q0");
    sc_trace(mVcdFile, data_5_V_address0, "(port)data_5_V_address0");
    sc_trace(mVcdFile, data_5_V_ce0, "(port)data_5_V_ce0");
    sc_trace(mVcdFile, data_5_V_q0, "(port)data_5_V_q0");
    sc_trace(mVcdFile, data_6_V_address0, "(port)data_6_V_address0");
    sc_trace(mVcdFile, data_6_V_ce0, "(port)data_6_V_ce0");
    sc_trace(mVcdFile, data_6_V_q0, "(port)data_6_V_q0");
    sc_trace(mVcdFile, data_7_V_address0, "(port)data_7_V_address0");
    sc_trace(mVcdFile, data_7_V_ce0, "(port)data_7_V_ce0");
    sc_trace(mVcdFile, data_7_V_q0, "(port)data_7_V_q0");
    sc_trace(mVcdFile, res_0_V_address0, "(port)res_0_V_address0");
    sc_trace(mVcdFile, res_0_V_ce0, "(port)res_0_V_ce0");
    sc_trace(mVcdFile, res_0_V_we0, "(port)res_0_V_we0");
    sc_trace(mVcdFile, res_0_V_d0, "(port)res_0_V_d0");
    sc_trace(mVcdFile, res_1_V_address0, "(port)res_1_V_address0");
    sc_trace(mVcdFile, res_1_V_ce0, "(port)res_1_V_ce0");
    sc_trace(mVcdFile, res_1_V_we0, "(port)res_1_V_we0");
    sc_trace(mVcdFile, res_1_V_d0, "(port)res_1_V_d0");
    sc_trace(mVcdFile, res_2_V_address0, "(port)res_2_V_address0");
    sc_trace(mVcdFile, res_2_V_ce0, "(port)res_2_V_ce0");
    sc_trace(mVcdFile, res_2_V_we0, "(port)res_2_V_we0");
    sc_trace(mVcdFile, res_2_V_d0, "(port)res_2_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, w10_V_address0, "w10_V_address0");
    sc_trace(mVcdFile, w10_V_ce0, "w10_V_ce0");
    sc_trace(mVcdFile, w10_V_q0, "w10_V_q0");
    sc_trace(mVcdFile, b10_V_address0, "b10_V_address0");
    sc_trace(mVcdFile, b10_V_ce0, "b10_V_ce0");
    sc_trace(mVcdFile, b10_V_q0, "b10_V_q0");
    sc_trace(mVcdFile, ii_9_fu_392_p2, "ii_9_fu_392_p2");
    sc_trace(mVcdFile, ii_9_reg_710, "ii_9_reg_710");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_fu_386_p2, "tmp_fu_386_p2");
    sc_trace(mVcdFile, tmp_240_fu_508_p2, "tmp_240_fu_508_p2");
    sc_trace(mVcdFile, tmp_240_reg_755, "tmp_240_reg_755");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, OP1_V_cast_fu_514_p1, "OP1_V_cast_fu_514_p1");
    sc_trace(mVcdFile, OP1_V_cast_reg_760, "OP1_V_cast_reg_760");
    sc_trace(mVcdFile, jj_5_fu_528_p2, "jj_5_fu_528_p2");
    sc_trace(mVcdFile, jj_5_reg_768, "jj_5_reg_768");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, index_fu_534_p2, "index_fu_534_p2");
    sc_trace(mVcdFile, index_reg_773, "index_reg_773");
    sc_trace(mVcdFile, tmp_243_fu_522_p2, "tmp_243_fu_522_p2");
    sc_trace(mVcdFile, tmp_246_fu_542_p1, "tmp_246_fu_542_p1");
    sc_trace(mVcdFile, tmp_246_reg_778, "tmp_246_reg_778");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, w10_V_load_reg_788, "w10_V_load_reg_788");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, grp_fu_702_p2, "grp_fu_702_p2");
    sc_trace(mVcdFile, p_Val2_s_reg_798, "p_Val2_s_reg_798");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, iacc_3_fu_566_p2, "iacc_3_fu_566_p2");
    sc_trace(mVcdFile, iacc_3_reg_806, "iacc_3_reg_806");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, tmp_242_fu_572_p1, "tmp_242_fu_572_p1");
    sc_trace(mVcdFile, tmp_242_reg_811, "tmp_242_reg_811");
    sc_trace(mVcdFile, tmp_s_fu_560_p2, "tmp_s_fu_560_p2");
    sc_trace(mVcdFile, b10_V_load_reg_821, "b10_V_load_reg_821");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ii_10_fu_587_p2, "ii_10_fu_587_p2");
    sc_trace(mVcdFile, ii_10_reg_829, "ii_10_reg_829");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, tmp_245_fu_619_p2, "tmp_245_fu_619_p2");
    sc_trace(mVcdFile, tmp_245_reg_834, "tmp_245_reg_834");
    sc_trace(mVcdFile, tmp_241_fu_581_p2, "tmp_241_fu_581_p2");
    sc_trace(mVcdFile, jj_6_fu_635_p2, "jj_6_fu_635_p2");
    sc_trace(mVcdFile, jj_6_reg_842, "jj_6_reg_842");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, index_3_fu_641_p2, "index_3_fu_641_p2");
    sc_trace(mVcdFile, index_3_reg_847, "index_3_reg_847");
    sc_trace(mVcdFile, tmp_250_fu_629_p2, "tmp_250_fu_629_p2");
    sc_trace(mVcdFile, acc_V_addr_6_reg_852, "acc_V_addr_6_reg_852");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, acc_V_q0, "acc_V_q0");
    sc_trace(mVcdFile, p_Val2_29_reg_862, "p_Val2_29_reg_862");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, mult_V_q0, "mult_V_q0");
    sc_trace(mVcdFile, p_Val2_30_reg_867, "p_Val2_30_reg_867");
    sc_trace(mVcdFile, ires_3_fu_670_p2, "ires_3_fu_670_p2");
    sc_trace(mVcdFile, ires_3_reg_875, "ires_3_reg_875");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, tmp_244_fu_664_p2, "tmp_244_fu_664_p2");
    sc_trace(mVcdFile, mult_V_address0, "mult_V_address0");
    sc_trace(mVcdFile, mult_V_ce0, "mult_V_ce0");
    sc_trace(mVcdFile, mult_V_we0, "mult_V_we0");
    sc_trace(mVcdFile, mult_V_d0, "mult_V_d0");
    sc_trace(mVcdFile, acc_V_address0, "acc_V_address0");
    sc_trace(mVcdFile, acc_V_ce0, "acc_V_ce0");
    sc_trace(mVcdFile, acc_V_we0, "acc_V_we0");
    sc_trace(mVcdFile, acc_V_d0, "acc_V_d0");
    sc_trace(mVcdFile, ii_reg_317, "ii_reg_317");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, jj_reg_329, "jj_reg_329");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, iacc_reg_340, "iacc_reg_340");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ii2_reg_351, "ii2_reg_351");
    sc_trace(mVcdFile, jj3_reg_362, "jj3_reg_362");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, ires_reg_374, "ires_reg_374");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, newIndex_fu_402_p1, "newIndex_fu_402_p1");
    sc_trace(mVcdFile, tmp_251_fu_649_p1, "tmp_251_fu_649_p1");
    sc_trace(mVcdFile, tmp_252_fu_654_p1, "tmp_252_fu_654_p1");
    sc_trace(mVcdFile, tmp_249_fu_676_p1, "tmp_249_fu_676_p1");
    sc_trace(mVcdFile, newIndex9_fu_695_p1, "newIndex9_fu_695_p1");
    sc_trace(mVcdFile, b10_V_load_cast_fu_577_p1, "b10_V_load_cast_fu_577_p1");
    sc_trace(mVcdFile, p_Val2_s_70_fu_659_p2, "p_Val2_s_70_fu_659_p2");
    sc_trace(mVcdFile, arrayNo5_cast_fu_681_p4, "arrayNo5_cast_fu_681_p4");
    sc_trace(mVcdFile, tmp_469_fu_398_p1, "tmp_469_fu_398_p1");
    sc_trace(mVcdFile, arrayNo_fu_414_p4, "arrayNo_fu_414_p4");
    sc_trace(mVcdFile, cache_V_fu_460_p1, "cache_V_fu_460_p1");
    sc_trace(mVcdFile, cache_V_fu_460_p2, "cache_V_fu_460_p2");
    sc_trace(mVcdFile, cache_V_fu_460_p3, "cache_V_fu_460_p3");
    sc_trace(mVcdFile, cache_V_fu_460_p4, "cache_V_fu_460_p4");
    sc_trace(mVcdFile, cache_V_fu_460_p5, "cache_V_fu_460_p5");
    sc_trace(mVcdFile, cache_V_fu_460_p6, "cache_V_fu_460_p6");
    sc_trace(mVcdFile, cache_V_fu_460_p7, "cache_V_fu_460_p7");
    sc_trace(mVcdFile, cache_V_fu_460_p8, "cache_V_fu_460_p8");
    sc_trace(mVcdFile, cache_V_fu_460_p9, "cache_V_fu_460_p9");
    sc_trace(mVcdFile, tmp_470_fu_482_p1, "tmp_470_fu_482_p1");
    sc_trace(mVcdFile, p_shl_fu_486_p3, "p_shl_fu_486_p3");
    sc_trace(mVcdFile, tmp_471_fu_498_p2, "tmp_471_fu_498_p2");
    sc_trace(mVcdFile, p_shl_cast_fu_494_p1, "p_shl_cast_fu_494_p1");
    sc_trace(mVcdFile, p_shl7_cast_fu_504_p1, "p_shl7_cast_fu_504_p1");
    sc_trace(mVcdFile, cache_V_fu_460_p10, "cache_V_fu_460_p10");
    sc_trace(mVcdFile, jj_cast6_fu_518_p1, "jj_cast6_fu_518_p1");
    sc_trace(mVcdFile, index_cast_fu_539_p1, "index_cast_fu_539_p1");
    sc_trace(mVcdFile, tmp_472_fu_593_p1, "tmp_472_fu_593_p1");
    sc_trace(mVcdFile, p_shl8_fu_597_p3, "p_shl8_fu_597_p3");
    sc_trace(mVcdFile, tmp_473_fu_609_p2, "tmp_473_fu_609_p2");
    sc_trace(mVcdFile, p_shl8_cast_fu_605_p1, "p_shl8_cast_fu_605_p1");
    sc_trace(mVcdFile, p_shl9_cast_fu_615_p1, "p_shl9_cast_fu_615_p1");
    sc_trace(mVcdFile, jj3_cast3_fu_625_p1, "jj3_cast3_fu_625_p1");
    sc_trace(mVcdFile, index_3_cast_fu_646_p1, "index_3_cast_fu_646_p1");
    sc_trace(mVcdFile, tmp_474_fu_691_p1, "tmp_474_fu_691_p1");
    sc_trace(mVcdFile, grp_fu_702_p0, "grp_fu_702_p0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::~dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete w10_V_U;
    delete b10_V_U;
    delete mult_V_U;
    delete acc_V_U;
    delete myproject_mux_832_16_1_1_U672;
    delete myproject_mul_mul_16s_12s_26_3_1_U673;
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(tmp_244_fu_664_p2.read(), ap_const_lv1_1) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_fu_386_p2.read(), ap_const_lv1_1))) {
        iacc_reg_340 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        iacc_reg_340 = iacc_3_reg_806.read();
    }
    if ((esl_seteq<1,1,1>(tmp_s_fu_560_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        ii2_reg_351 = ap_const_lv8_0;
    } else if ((esl_seteq<1,1,1>(tmp_250_fu_629_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        ii2_reg_351 = ii_10_reg_829.read();
    }
    if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ii_reg_317 = ap_const_lv8_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(tmp_243_fu_522_p2.read(), ap_const_lv1_1))) {
        ii_reg_317 = ii_9_reg_710.read();
    }
    if ((esl_seteq<1,1,1>(tmp_241_fu_581_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        ires_reg_374 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        ires_reg_374 = ires_3_reg_875.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        jj3_reg_362 = jj_6_reg_842.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
                esl_seteq<1,1,1>(tmp_241_fu_581_p2.read(), ap_const_lv1_0))) {
        jj3_reg_362 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        jj_reg_329 = jj_5_reg_768.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        jj_reg_329 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        OP1_V_cast_reg_760 = OP1_V_cast_fu_514_p1.read();
        tmp_240_reg_755 = tmp_240_fu_508_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        acc_V_addr_6_reg_852 =  (sc_lv<3>) (tmp_251_fu_649_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        b10_V_load_reg_821 = b10_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        iacc_3_reg_806 = iacc_3_fu_566_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        ii_10_reg_829 = ii_10_fu_587_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        ii_9_reg_710 = ii_9_fu_392_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(tmp_250_fu_629_p2.read(), ap_const_lv1_0))) {
        index_3_reg_847 = index_3_fu_641_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(tmp_243_fu_522_p2.read(), ap_const_lv1_0))) {
        index_reg_773 = index_fu_534_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        ires_3_reg_875 = ires_3_fu_670_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        jj_5_reg_768 = jj_5_fu_528_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        jj_6_reg_842 = jj_6_fu_635_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        p_Val2_29_reg_862 = acc_V_q0.read();
        p_Val2_30_reg_867 = mult_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        p_Val2_s_reg_798 = grp_fu_702_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(tmp_s_fu_560_p2.read(), ap_const_lv1_0))) {
        tmp_242_reg_811 = tmp_242_fu_572_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(tmp_241_fu_581_p2.read(), ap_const_lv1_0))) {
        tmp_245_reg_834 = tmp_245_fu_619_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        tmp_246_reg_778 = tmp_246_fu_542_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        w10_V_load_reg_788 = w10_V_q0.read();
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_OP1_V_cast_fu_514_p1() {
    OP1_V_cast_fu_514_p1 = esl_sext<26,16>(cache_V_fu_460_p10.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_acc_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        acc_V_address0 =  (sc_lv<3>) (tmp_249_fu_676_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        acc_V_address0 = acc_V_addr_6_reg_852.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        acc_V_address0 =  (sc_lv<3>) (tmp_251_fu_649_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        acc_V_address0 =  (sc_lv<3>) (tmp_242_reg_811.read());
    } else {
        acc_V_address0 = "XXX";
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_acc_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        acc_V_ce0 = ap_const_logic_1;
    } else {
        acc_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_acc_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        acc_V_d0 = p_Val2_s_70_fu_659_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        acc_V_d0 = b10_V_load_cast_fu_577_p1.read();
    } else {
        acc_V_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_acc_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        acc_V_we0 = ap_const_logic_1;
    } else {
        acc_V_we0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(tmp_244_fu_664_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(tmp_244_fu_664_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_arrayNo5_cast_fu_681_p4() {
    arrayNo5_cast_fu_681_p4 = ires_reg_374.read().range(2, 1);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_arrayNo_fu_414_p4() {
    arrayNo_fu_414_p4 = ii_reg_317.read().range(7, 4);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_b10_V_address0() {
    b10_V_address0 =  (sc_lv<3>) (tmp_242_fu_572_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_b10_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        b10_V_ce0 = ap_const_logic_1;
    } else {
        b10_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_b10_V_load_cast_fu_577_p1() {
    b10_V_load_cast_fu_577_p1 = esl_sext<16,11>(b10_V_load_reg_821.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_cache_V_fu_460_p1() {
    cache_V_fu_460_p1 = esl_zext<16,15>(data_0_V_q0.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_cache_V_fu_460_p2() {
    cache_V_fu_460_p2 = esl_zext<16,15>(data_1_V_q0.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_cache_V_fu_460_p3() {
    cache_V_fu_460_p3 = esl_zext<16,15>(data_2_V_q0.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_cache_V_fu_460_p4() {
    cache_V_fu_460_p4 = esl_zext<16,15>(data_3_V_q0.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_cache_V_fu_460_p5() {
    cache_V_fu_460_p5 = esl_zext<16,15>(data_4_V_q0.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_cache_V_fu_460_p6() {
    cache_V_fu_460_p6 = esl_zext<16,15>(data_5_V_q0.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_cache_V_fu_460_p7() {
    cache_V_fu_460_p7 = esl_zext<16,15>(data_6_V_q0.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_cache_V_fu_460_p8() {
    cache_V_fu_460_p8 = esl_zext<16,15>(data_7_V_q0.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_cache_V_fu_460_p9() {
    cache_V_fu_460_p9 = esl_zext<32,4>(arrayNo_fu_414_p4.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_data_0_V_address0() {
    data_0_V_address0 =  (sc_lv<4>) (newIndex_fu_402_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_data_0_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_0_V_ce0 = ap_const_logic_1;
    } else {
        data_0_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_data_1_V_address0() {
    data_1_V_address0 =  (sc_lv<4>) (newIndex_fu_402_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_data_1_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_1_V_ce0 = ap_const_logic_1;
    } else {
        data_1_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_data_2_V_address0() {
    data_2_V_address0 =  (sc_lv<4>) (newIndex_fu_402_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_data_2_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_2_V_ce0 = ap_const_logic_1;
    } else {
        data_2_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_data_3_V_address0() {
    data_3_V_address0 =  (sc_lv<4>) (newIndex_fu_402_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_data_3_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_3_V_ce0 = ap_const_logic_1;
    } else {
        data_3_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_data_4_V_address0() {
    data_4_V_address0 =  (sc_lv<4>) (newIndex_fu_402_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_data_4_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_4_V_ce0 = ap_const_logic_1;
    } else {
        data_4_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_data_5_V_address0() {
    data_5_V_address0 =  (sc_lv<4>) (newIndex_fu_402_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_data_5_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_5_V_ce0 = ap_const_logic_1;
    } else {
        data_5_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_data_6_V_address0() {
    data_6_V_address0 =  (sc_lv<4>) (newIndex_fu_402_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_data_6_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_6_V_ce0 = ap_const_logic_1;
    } else {
        data_6_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_data_7_V_address0() {
    data_7_V_address0 =  (sc_lv<4>) (newIndex_fu_402_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_data_7_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_7_V_ce0 = ap_const_logic_1;
    } else {
        data_7_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_grp_fu_702_p0() {
    grp_fu_702_p0 =  (sc_lv<16>) (OP1_V_cast_reg_760.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_iacc_3_fu_566_p2() {
    iacc_3_fu_566_p2 = (!iacc_reg_340.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(iacc_reg_340.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ii_10_fu_587_p2() {
    ii_10_fu_587_p2 = (!ii2_reg_351.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(ii2_reg_351.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ii_9_fu_392_p2() {
    ii_9_fu_392_p2 = (!ii_reg_317.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(ii_reg_317.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_index_3_cast_fu_646_p1() {
    index_3_cast_fu_646_p1 = esl_sext<32,11>(index_3_reg_847.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_index_3_fu_641_p2() {
    index_3_fu_641_p2 = (!tmp_245_reg_834.read().is_01() || !jj3_cast3_fu_625_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_245_reg_834.read()) + sc_biguint<11>(jj3_cast3_fu_625_p1.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_index_cast_fu_539_p1() {
    index_cast_fu_539_p1 = esl_sext<32,11>(index_reg_773.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_index_fu_534_p2() {
    index_fu_534_p2 = (!tmp_240_reg_755.read().is_01() || !jj_cast6_fu_518_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_240_reg_755.read()) + sc_biguint<11>(jj_cast6_fu_518_p1.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ires_3_fu_670_p2() {
    ires_3_fu_670_p2 = (!ires_reg_374.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(ires_reg_374.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_jj3_cast3_fu_625_p1() {
    jj3_cast3_fu_625_p1 = esl_zext<11,3>(jj3_reg_362.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_jj_5_fu_528_p2() {
    jj_5_fu_528_p2 = (!jj_reg_329.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(jj_reg_329.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_jj_6_fu_635_p2() {
    jj_6_fu_635_p2 = (!jj3_reg_362.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(jj3_reg_362.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_jj_cast6_fu_518_p1() {
    jj_cast6_fu_518_p1 = esl_zext<11,3>(jj_reg_329.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_mult_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        mult_V_address0 =  (sc_lv<10>) (tmp_252_fu_654_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        mult_V_address0 =  (sc_lv<10>) (tmp_246_reg_778.read());
    } else {
        mult_V_address0 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_mult_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        mult_V_ce0 = ap_const_logic_1;
    } else {
        mult_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_mult_V_d0() {
    mult_V_d0 = p_Val2_s_reg_798.read().range(25, 10);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_mult_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        mult_V_we0 = ap_const_logic_1;
    } else {
        mult_V_we0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_newIndex9_fu_695_p1() {
    newIndex9_fu_695_p1 = esl_zext<64,1>(tmp_474_fu_691_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_newIndex_fu_402_p1() {
    newIndex_fu_402_p1 = esl_zext<64,4>(tmp_469_fu_398_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_p_Val2_s_70_fu_659_p2() {
    p_Val2_s_70_fu_659_p2 = (!p_Val2_29_reg_862.read().is_01() || !p_Val2_30_reg_867.read().is_01())? sc_lv<16>(): (sc_biguint<16>(p_Val2_29_reg_862.read()) + sc_biguint<16>(p_Val2_30_reg_867.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_p_shl7_cast_fu_504_p1() {
    p_shl7_cast_fu_504_p1 = esl_zext<11,8>(tmp_471_fu_498_p2.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_p_shl8_cast_fu_605_p1() {
    p_shl8_cast_fu_605_p1 = esl_zext<11,10>(p_shl8_fu_597_p3.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_p_shl8_fu_597_p3() {
    p_shl8_fu_597_p3 = esl_concat<7,3>(tmp_472_fu_593_p1.read(), ap_const_lv3_0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_p_shl9_cast_fu_615_p1() {
    p_shl9_cast_fu_615_p1 = esl_zext<11,8>(tmp_473_fu_609_p2.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_p_shl_cast_fu_494_p1() {
    p_shl_cast_fu_494_p1 = esl_zext<11,10>(p_shl_fu_486_p3.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_p_shl_fu_486_p3() {
    p_shl_fu_486_p3 = esl_concat<7,3>(tmp_470_fu_482_p1.read(), ap_const_lv3_0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_res_0_V_address0() {
    res_0_V_address0 =  (sc_lv<1>) (newIndex9_fu_695_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_res_0_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        res_0_V_ce0 = ap_const_logic_1;
    } else {
        res_0_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_res_0_V_d0() {
    res_0_V_d0 = acc_V_q0.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_res_0_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && 
         esl_seteq<1,2,2>(arrayNo5_cast_fu_681_p4.read(), ap_const_lv2_0))) {
        res_0_V_we0 = ap_const_logic_1;
    } else {
        res_0_V_we0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_res_1_V_address0() {
    res_1_V_address0 =  (sc_lv<1>) (newIndex9_fu_695_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_res_1_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        res_1_V_ce0 = ap_const_logic_1;
    } else {
        res_1_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_res_1_V_d0() {
    res_1_V_d0 = acc_V_q0.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_res_1_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && 
         esl_seteq<1,2,2>(arrayNo5_cast_fu_681_p4.read(), ap_const_lv2_1))) {
        res_1_V_we0 = ap_const_logic_1;
    } else {
        res_1_V_we0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_res_2_V_address0() {
    res_2_V_address0 =  (sc_lv<1>) (newIndex9_fu_695_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_res_2_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        res_2_V_ce0 = ap_const_logic_1;
    } else {
        res_2_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_res_2_V_d0() {
    res_2_V_d0 = acc_V_q0.read();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_res_2_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && 
         !esl_seteq<1,2,2>(arrayNo5_cast_fu_681_p4.read(), ap_const_lv2_0) && 
         !esl_seteq<1,2,2>(arrayNo5_cast_fu_681_p4.read(), ap_const_lv2_1))) {
        res_2_V_we0 = ap_const_logic_1;
    } else {
        res_2_V_we0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_240_fu_508_p2() {
    tmp_240_fu_508_p2 = (!p_shl_cast_fu_494_p1.read().is_01() || !p_shl7_cast_fu_504_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl_cast_fu_494_p1.read()) - sc_biguint<11>(p_shl7_cast_fu_504_p1.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_241_fu_581_p2() {
    tmp_241_fu_581_p2 = (!ii2_reg_351.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(ii2_reg_351.read() == ap_const_lv8_80);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_242_fu_572_p1() {
    tmp_242_fu_572_p1 = esl_zext<64,3>(iacc_reg_340.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_243_fu_522_p2() {
    tmp_243_fu_522_p2 = (!jj_reg_329.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(jj_reg_329.read() == ap_const_lv3_6);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_244_fu_664_p2() {
    tmp_244_fu_664_p2 = (!ires_reg_374.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(ires_reg_374.read() == ap_const_lv3_6);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_245_fu_619_p2() {
    tmp_245_fu_619_p2 = (!p_shl8_cast_fu_605_p1.read().is_01() || !p_shl9_cast_fu_615_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl8_cast_fu_605_p1.read()) - sc_biguint<11>(p_shl9_cast_fu_615_p1.read()));
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_246_fu_542_p1() {
    tmp_246_fu_542_p1 = esl_zext<64,32>(index_cast_fu_539_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_249_fu_676_p1() {
    tmp_249_fu_676_p1 = esl_zext<64,3>(ires_reg_374.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_250_fu_629_p2() {
    tmp_250_fu_629_p2 = (!jj3_reg_362.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(jj3_reg_362.read() == ap_const_lv3_6);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_251_fu_649_p1() {
    tmp_251_fu_649_p1 = esl_zext<64,3>(jj3_reg_362.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_252_fu_654_p1() {
    tmp_252_fu_654_p1 = esl_zext<64,32>(index_3_cast_fu_646_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_469_fu_398_p1() {
    tmp_469_fu_398_p1 = ii_reg_317.read().range(4-1, 0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_470_fu_482_p1() {
    tmp_470_fu_482_p1 = ii_reg_317.read().range(7-1, 0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_471_fu_498_p2() {
    tmp_471_fu_498_p2 = (!ap_const_lv8_1.is_01())? sc_lv<8>(): ii_reg_317.read() << (unsigned short)ap_const_lv8_1.to_uint();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_472_fu_593_p1() {
    tmp_472_fu_593_p1 = ii2_reg_351.read().range(7-1, 0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_473_fu_609_p2() {
    tmp_473_fu_609_p2 = (!ap_const_lv8_1.is_01())? sc_lv<8>(): ii2_reg_351.read() << (unsigned short)ap_const_lv8_1.to_uint();
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_474_fu_691_p1() {
    tmp_474_fu_691_p1 = ires_reg_374.read().range(1-1, 0);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_fu_386_p2() {
    tmp_fu_386_p2 = (!ii_reg_317.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(ii_reg_317.read() == ap_const_lv8_80);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_tmp_s_fu_560_p2() {
    tmp_s_fu_560_p2 = (!iacc_reg_340.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(iacc_reg_340.read() == ap_const_lv3_6);
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_w10_V_address0() {
    w10_V_address0 =  (sc_lv<10>) (tmp_246_fu_542_p1.read());
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_w10_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        w10_V_ce0 = ap_const_logic_1;
    } else {
        w10_V_ce0 = ap_const_logic_0;
    }
}

void dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config10_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_fu_386_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(tmp_243_fu_522_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(tmp_s_fu_560_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 8192 : 
            if ((esl_seteq<1,1,1>(tmp_241_fu_581_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
                ap_NS_fsm = ap_ST_fsm_state19;
            } else {
                ap_NS_fsm = ap_ST_fsm_state15;
            }
            break;
        case 16384 : 
            if ((esl_seteq<1,1,1>(tmp_250_fu_629_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 262144 : 
            if ((esl_seteq<1,1,1>(tmp_244_fu_664_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state20;
            }
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<20>) ("XXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

