// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s_HH_
#define _relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "myproject_mux_832_16_1_1.h"

namespace ap_rtl {

struct relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s : public sc_module {
    // Port declarations 63
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<12> > data_0_V_address0;
    sc_out< sc_logic > data_0_V_ce0;
    sc_in< sc_lv<16> > data_0_V_q0;
    sc_out< sc_lv<12> > data_1_V_address0;
    sc_out< sc_logic > data_1_V_ce0;
    sc_in< sc_lv<16> > data_1_V_q0;
    sc_out< sc_lv<12> > data_2_V_address0;
    sc_out< sc_logic > data_2_V_ce0;
    sc_in< sc_lv<16> > data_2_V_q0;
    sc_out< sc_lv<12> > data_3_V_address0;
    sc_out< sc_logic > data_3_V_ce0;
    sc_in< sc_lv<16> > data_3_V_q0;
    sc_out< sc_lv<12> > data_4_V_address0;
    sc_out< sc_logic > data_4_V_ce0;
    sc_in< sc_lv<16> > data_4_V_q0;
    sc_out< sc_lv<12> > data_5_V_address0;
    sc_out< sc_logic > data_5_V_ce0;
    sc_in< sc_lv<16> > data_5_V_q0;
    sc_out< sc_lv<12> > data_6_V_address0;
    sc_out< sc_logic > data_6_V_ce0;
    sc_in< sc_lv<16> > data_6_V_q0;
    sc_out< sc_lv<12> > data_7_V_address0;
    sc_out< sc_logic > data_7_V_ce0;
    sc_in< sc_lv<16> > data_7_V_q0;
    sc_out< sc_lv<12> > res_0_V_address0;
    sc_out< sc_logic > res_0_V_ce0;
    sc_out< sc_logic > res_0_V_we0;
    sc_out< sc_lv<15> > res_0_V_d0;
    sc_out< sc_lv<12> > res_1_V_address0;
    sc_out< sc_logic > res_1_V_ce0;
    sc_out< sc_logic > res_1_V_we0;
    sc_out< sc_lv<15> > res_1_V_d0;
    sc_out< sc_lv<12> > res_2_V_address0;
    sc_out< sc_logic > res_2_V_ce0;
    sc_out< sc_logic > res_2_V_we0;
    sc_out< sc_lv<15> > res_2_V_d0;
    sc_out< sc_lv<12> > res_3_V_address0;
    sc_out< sc_logic > res_3_V_ce0;
    sc_out< sc_logic > res_3_V_we0;
    sc_out< sc_lv<15> > res_3_V_d0;
    sc_out< sc_lv<12> > res_4_V_address0;
    sc_out< sc_logic > res_4_V_ce0;
    sc_out< sc_logic > res_4_V_we0;
    sc_out< sc_lv<15> > res_4_V_d0;
    sc_out< sc_lv<12> > res_5_V_address0;
    sc_out< sc_logic > res_5_V_ce0;
    sc_out< sc_logic > res_5_V_we0;
    sc_out< sc_lv<15> > res_5_V_d0;
    sc_out< sc_lv<12> > res_6_V_address0;
    sc_out< sc_logic > res_6_V_ce0;
    sc_out< sc_logic > res_6_V_we0;
    sc_out< sc_lv<15> > res_6_V_d0;
    sc_out< sc_lv<12> > res_7_V_address0;
    sc_out< sc_logic > res_7_V_ce0;
    sc_out< sc_logic > res_7_V_we0;
    sc_out< sc_lv<15> > res_7_V_d0;


    // Module declarations
    relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s(sc_module_name name);
    SC_HAS_PROCESS(relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s);

    ~relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s();

    sc_trace_file* mVcdFile;

    myproject_mux_832_16_1_1<1,1,16,16,16,16,16,16,16,16,32,16>* myproject_mux_832_16_1_1_U550;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<15> > ii_3_fu_322_p2;
    sc_signal< sc_lv<15> > ii_3_reg_418;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<31> > next_mul_fu_328_p2;
    sc_signal< sc_lv<31> > next_mul_reg_423;
    sc_signal< sc_lv<1> > tmp_fu_316_p2;
    sc_signal< sc_lv<4> > tmp_29_reg_428;
    sc_signal< sc_lv<64> > newIndex1_fu_344_p1;
    sc_signal< sc_lv<64> > newIndex1_reg_433;
    sc_signal< sc_lv<16> > data_0_V_load_reg_485;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<16> > data_1_V_load_reg_490;
    sc_signal< sc_lv<16> > data_2_V_load_reg_495;
    sc_signal< sc_lv<16> > data_3_V_load_reg_500;
    sc_signal< sc_lv<16> > data_4_V_load_reg_505;
    sc_signal< sc_lv<16> > data_5_V_load_reg_510;
    sc_signal< sc_lv<16> > data_6_V_load_reg_515;
    sc_signal< sc_lv<16> > data_7_V_load_reg_520;
    sc_signal< sc_lv<15> > tmp_30_fu_373_p1;
    sc_signal< sc_lv<15> > tmp_30_reg_525;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > tmp_s_fu_377_p2;
    sc_signal< sc_lv<1> > tmp_s_reg_530;
    sc_signal< sc_lv<15> > next_urem_fu_397_p2;
    sc_signal< sc_lv<15> > next_urem_reg_535;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<15> > idx_urem_fu_408_p3;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<15> > ii_reg_282;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<31> > phi_mul_reg_293;
    sc_signal< sc_lv<15> > phi_urem_reg_304;
    sc_signal< sc_lv<15> > datareg_V_3_fu_383_p3;
    sc_signal< sc_lv<32> > datareg_V_fu_359_p9;
    sc_signal< sc_lv<16> > datareg_V_fu_359_p10;
    sc_signal< sc_lv<1> > tmp_31_fu_403_p2;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_state2;
    static const sc_lv<6> ap_ST_fsm_state3;
    static const sc_lv<6> ap_ST_fsm_state4;
    static const sc_lv<6> ap_ST_fsm_state5;
    static const sc_lv<6> ap_ST_fsm_state6;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<15> ap_const_lv15_0;
    static const sc_lv<31> ap_const_lv31_0;
    static const sc_lv<4> ap_const_lv4_6;
    static const sc_lv<4> ap_const_lv4_5;
    static const sc_lv<4> ap_const_lv4_4;
    static const sc_lv<4> ap_const_lv4_3;
    static const sc_lv<4> ap_const_lv4_2;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<15> ap_const_lv15_5900;
    static const sc_lv<15> ap_const_lv15_1;
    static const sc_lv<31> ap_const_lv31_B818;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<15> ap_const_lv15_B20;
    static const sc_lv<1> ap_const_lv1_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_block_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_data_0_V_address0();
    void thread_data_0_V_ce0();
    void thread_data_1_V_address0();
    void thread_data_1_V_ce0();
    void thread_data_2_V_address0();
    void thread_data_2_V_ce0();
    void thread_data_3_V_address0();
    void thread_data_3_V_ce0();
    void thread_data_4_V_address0();
    void thread_data_4_V_ce0();
    void thread_data_5_V_address0();
    void thread_data_5_V_ce0();
    void thread_data_6_V_address0();
    void thread_data_6_V_ce0();
    void thread_data_7_V_address0();
    void thread_data_7_V_ce0();
    void thread_datareg_V_3_fu_383_p3();
    void thread_datareg_V_fu_359_p9();
    void thread_idx_urem_fu_408_p3();
    void thread_ii_3_fu_322_p2();
    void thread_newIndex1_fu_344_p1();
    void thread_next_mul_fu_328_p2();
    void thread_next_urem_fu_397_p2();
    void thread_res_0_V_address0();
    void thread_res_0_V_ce0();
    void thread_res_0_V_d0();
    void thread_res_0_V_we0();
    void thread_res_1_V_address0();
    void thread_res_1_V_ce0();
    void thread_res_1_V_d0();
    void thread_res_1_V_we0();
    void thread_res_2_V_address0();
    void thread_res_2_V_ce0();
    void thread_res_2_V_d0();
    void thread_res_2_V_we0();
    void thread_res_3_V_address0();
    void thread_res_3_V_ce0();
    void thread_res_3_V_d0();
    void thread_res_3_V_we0();
    void thread_res_4_V_address0();
    void thread_res_4_V_ce0();
    void thread_res_4_V_d0();
    void thread_res_4_V_we0();
    void thread_res_5_V_address0();
    void thread_res_5_V_ce0();
    void thread_res_5_V_d0();
    void thread_res_5_V_we0();
    void thread_res_6_V_address0();
    void thread_res_6_V_ce0();
    void thread_res_6_V_d0();
    void thread_res_6_V_we0();
    void thread_res_7_V_address0();
    void thread_res_7_V_ce0();
    void thread_res_7_V_d0();
    void thread_res_7_V_we0();
    void thread_tmp_30_fu_373_p1();
    void thread_tmp_31_fu_403_p2();
    void thread_tmp_fu_316_p2();
    void thread_tmp_s_fu_377_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
