Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    conv2d_1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    conv2d_1_input:
      Precision:
        result: fixed<16,6>
      Trace: false
    conv2d_1_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_1_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_2:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_2_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_3:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_3_softmax:
      Precision:
        result: fixed<16,6>
      Trace: false
    flatten_1:
      Precision:
        result: fixed<16,6>
      Trace: false
    max_pooling2d_1:
      Precision:
        result: fixed<16,6>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model '/home/abhinit_singh/hls4ml_original/my-hls-test5/keras_model.h5'
OutputDir: /home/abhinit_singh/hls4ml_original/my-hls-test5
OutputPredictions: null
Part: xc7a200tfbg676-2
ProjectName: myproject
Stamp: 8d4eE1f7
Version: 1.0.0
